= අකුරූපණ සිංහල ගැටපද එළිය

*සිංහලානුවාදය සඳහා සංඥාපනය*

පරිගණක භාවිතයෙන් අකුරු රූප (font) නිර්මාණය කිරීම ලක්දිව මේ වනවිට එතරම්
ප්‍රකට කටයුත්තක් නොවේ. එහෙයින් පාඨකයා නවකයෙකු සේ සළකා ඔහු/ අැය මේ
ක්‍රියාවලිය කෙරෙහි අාසක්ත වන අයුරින් අනුවර්තනය කිරීමට හැකිතාක් උත්සාහ
දරා අැත. තවද මේ සඳහා අාසක්ත වේ යැයි සිතනු ලබන පිරිස පරිගණක
සාක්ෂරතාවයෙන් හෙබි ස්ව-අධ්‍යනය කෙරෙහි රුචි පිරිසක් යැයි සිතනු ලබන හෙයින්
ඔවුනගේ පහසුව උදෙසා නව ගැටපද (පාරිභාෂික යෙදුම්) අසලින් එ් සඳහා වන
ඉංග්‍රීසි යෙදුමද දක්වා අැත.

අනුවාදයක් යනු අදහස (සුගම ව) වෙනත් බසකට නැංවීම මිස වචන පරිවර්තනයක්
නොවේ. මෙය අනුවාදයකි. එහෙයින් මෙහි අරමුණ මුල් භාෂාවෙන් ජනිත කරන අදහස
ගෝචර කරගැනීම ට අපහසු වන අයට පහසුවෙන් මුල් අදහස ජනිත කරගැනීමට ඔවුන්
දන්නා සංකල්ප අැසුරින් එය විස්තර කිරීමයි. එහිදී ද්වියීතික බසෙහි යෙදුමක්
ද්වියීතික බසෙහි සංකල්ප අැසුරින් තේරුම් ගන්නවාට වඩා සරලව මූලික බසෙහි
සංකල්ප අැසුරින් තේරුම්ගත හැකි අවස්ථාවලදී (වචනවල සුලභතාව නැතහොත්
ශබ්දකෝෂවල සුලභතාව අාදී කාරණා නිසා) මුල් වචනය එලෙසින්ම තිබෙන්නට හරින
ලදී.

විශේෂයෙන් සඳහන් කර නැතිවිට, සියලුම අර්ථදැක්වීම් කර අැත්තේ කඩදාසියක් මත
කරන ලද මුද්‍රණයකට සාපේක්ෂවයි. (එනම් මුද්‍රණ යන්ත්‍රයේ මුද්‍රණ තහඩුව/
සෘණ ඵලකය සලකා නොවේ)

මේ දැනුම ඉංග්‍රීසි සහ එ් අාශ්‍රිත අනෙක් භාෂා අැසුරෙහි වර්ධනය වූවක්
බැවින් බොහෝ අර්ථ දැක්වීම් වර්ධනය වී අැත්තේ එ් භාෂා සහ එ් හෝඩිවල
ස්වරූප අාශ්‍රය කරගෙනයි. එහෙයින් මේ දැනුම සිංහලෙන් ව්‍යාප්ත කිරීමේදී
(රවුම් හැඩතල බෙහෙවින් භාවිතා වන) සිංහලය සඳහා නව අර්ථ දැක්වීම් කිරීමට
සිදුවිය හැකිය.

ඔ්නෑම මැනුවලයක් (අත් පොතක්) එය භාවිතා කරන්නේයැයි සිතනු ලබන
පරිශීලකයාගේ උපරිම පහසුව සැළසීමට බැඳී සිටින හෙයින් මෙම මැනුවලය හෙවත්
‘ප්‍රධාන මැනුවලය’ පාඨකයාට වඩාත් හුරු පුරුදු සහ වඩාත් රුචිකර වේ යැයි
සිතන එදිනෙදා ව්‍යවහාර භාෂාවට වඩාත් අාසන්න ලෙසකින් තැබීමටත් පාරිභාෂික පද
විවරණය හෙවත් ‘ගැටපද එළිය’ එහි උපරිම උපයෝග්‍යතාවයෙහි තැබීම සඳහා එය
පාරිභාෂික තාක්ෂණික බසට වඩාත් අාසන්නව තැබීමටත් තීරණය කරන ලදී.

A

Abjad අබ්ජාඩ් ක්‍රමය

සෙමිටික් (හිබෲ, අරාබි ආදී...) භාෂාවල ලේඛණ ක්‍රමය හැඳින්වීමට යොදන
තාක්ෂණික යෙදුම. මෙහිදී සියලුම ව්‍යංජන අක්ෂර ලිඛිත සංකේත ස්වරූපයෙන්
දැක්විය හැකි නමුත් ව්‍යංජන අක්ෂර දෙකක් අතර යෙදිය යුතු ස්වර අක්ෂරය
කුමක්දැයි අනුමාන කරන්නට කියවන්නාට සිදුවේ.

පුරාණ ෆිනීෂියානු බස ස්වර අක්ෂර රහිත ව්‍යංජනාක්ෂර පමණක් තිබූ ශුද්ධ
අබ්ජාඩ් බසක් වන අතර හිබෲ සහ අරාබි භාෂා දෙකෙහි අතිරේක ස්වර සංකේත භාවිතා
වන බැවින් අශුද්ධ අබ්ජාඩ් භාෂා ලෙස හැඳින්වේ.

වැඩි විස්තර සඳහා හෝඩිය, අබුගිඩා ක්‍රමය, මාත්‍රාව යටතේ සහ
http://en.wikipedia.org/wiki/Abjad පිටුව යටතේ බලන්න.

Abugida අබුගිඩා ක්‍රමය

අක්ෂර සහ මාත්‍රා ලේඛණ ක්‍රම දෙකෙහි සංකලනයකි. අබුගිඩා ලේඛණ ක්‍රමය සඳහා
හොඳම නිදර්ශන ඉන්දු ලේඛණ ක්‍රමවල ස්වරූපය තුල හඳුනාගත හැක.

පොදුවේ බොහෝ අබුගිඩා ලේඛණ ක්‍රම තුල ව්‍යංජන අක්ෂර සඳහා ස්වාධීන කේත අඩංගු
වන අතර ඒවා සැමවිටම පාහේ නිශ්චිත මූලික ස්වරයක් සමඟ බැඳී පවතී. ඊට වෙනස්
ස්වරයන් හා සංයෝග වනවිට පිලි හෝ වෙනත් උච්චාරණ සලකුණු යෙදීමෙන් ව්‍යංජනය
වෙනස් කරනු ලැබේ.

අබුගිඩා ක්‍රමයේදී ඒ ඒ ව්‍යංජනයෙන් සංයුක්ත අක්ෂරයක් සෑදෙන විට ලැබෙන අවසාන
අක්ෂරවල ස්වරූපයන් එකම තේමාවක පවතින අතර මාත්‍රා ක්‍රමයේදී එකම
ව්‍යංජනයකින් සංයුක්ත අක්ෂර සෑදෙන විට ලැබෙන අවසාන අක්ෂර විවිධ ස්වරූප ගනී.

අබුගිඩා ක්‍රමය අබ්ජාඩ් ක්‍රමයෙන් වෙනස් වන්නේ අබුගිඩා ක්‍රමයේදී මූලික
ස්වරය හා සම්බන්ධ වනවිට හැර අනෙක් සෑමවිටම ස්වරය පිල්ලක් මඟින් ලකුණු
කලයුතු වීම මඟිනි.

වැඩි විස්තර සඳහා හෝඩිය, අබ්ජාඩ් ක්‍රමය , මාත්‍රාව යටතේ සහ
http://en.wikipedia.org/wiki/Abugida පිටුව යටතේ බලන්න.

Accent උච්චාරණ විධිය

උච්චාරණ සලකුණු යටතේ බලන්න.

Advance Width වර්ධිත පළල/ එකතුවන පළල

අකුරක ආරම්භයේ සිට ඊළඟ අකුරේ ආරම්භය දක්වා ඇති දුර. අක්ෂර පළල නමින්ද
හඳුන්වයි. වැඩි විස්තර සඳහා සිරස් එකතුවන පළල යටතේ බලන්න.

Alphabet හෝඩිය

භාෂාවක සියලුම ශබ්ධ අණු සඳහා වන ලිඛිත සංකේත මාලාව. ස්වර සහ ව්‍යංජන ලෙස
කොටස් දෙකකට හඳුනාගත හැක. න්‍යායිකව, වචනයක අඩංගු සියලුම ශබ්ධ අණු ඊට අදාල
නියමිත සංකේතයකින් පෙන්විය හැක.

වැඩි විස්තර සඳහා අබ්ජාඩ් ක්‍රමය, අබුගිඩා ක්‍රමය, මාත්‍රාව යටතේ සහ
http://en.wikipedia.org/wiki/Alphabet පිටුව යටතේ බලන්න.

Apple Advanced Typography ‘ඇපල්’ වර්ධිත අක්ෂර

මූලික සත්‍ය ප්‍රකාර ෆොන්ට (basic TrueType fonts) සඳහා ඇපල් සමාගම විසින්
සැකසූ දිගුව. සංධර්භානුකූල ආදේශනය, බැඳි අකුරු, අකුරු අතර පරතරය වෙනස්
කිරීම ආදී පහසුකම් අන්තර්ගත විය. විපරීත කළහැකි ෆොන්ට (distortable fonts)
ද මීට අදාල වේ.

Arm අත

ඉංග්‍රීසි සිම්පල් ආර් ( r ) අකුරේ දකුණට විහිදෙන ඉර.

Ascender නැග්මකය

ඉංග්‍රීසි සිම්පල් එක්ස් ( x ) අකුරට සාපේක්ෂව එහි උසින් ඉහලට නැඟෙන
සිම්පල් අකුරු කොටස්. සිම්පල් එච් ( h ), සිම්පල් ඩී ( d ) අකුරු වලට
නැග්මක තිබේ.

එක්ස් උස (X-height), කැපිටල් උස (Cap-height), බැස්මකය (Descender),
ඉක්මකය (Overshoot) සහ පාදම් රේඛාව (Baseline) යටතේ ත් බලන්න.

# Anchor Class නැංගුරම් පංතිය

මාක්-ටු-බේස් (mark-to-base) සහ වැල් අකුරු සඳහා වන GPOS උප-වගු, විශේෂ
වශයෙන් හැඳින්වීමට යෙදෙන යෙදුමකි.

Ascent ආරෝහණය

සාම්ප්‍රදායික මුද්‍රණ අක්ෂර නිර්මාණ විද්‍යාව ට අනුව, අකුරු පේළියක ඉහළ
සීමාවේ සිට ඊට ඉහළ අකුරු පේලියේ පාදම් රේඛාව ට ඇති දුර.

නූතන අක්ෂර නිර්මාණ විද්‍යාවේ දී නිර්වචකයන් මේ සඳහා විවිධ අර්ථ නිරූපණ
සපයා ඇත.

ATSUI

ඇපල් සමාගමේ වර්ධිත අක්ෂර නිර්මාණ (Apple’s advanced typographical
system). ‘ඇපල්’ වර්ධිත අක්ෂර (Apple Advanced Typography) නමින්ද
හඳුන්වයි.

B

Baseline පාදම් රේඛාව [line-through]*/ (තනි) රූල*

ලතින්, ග්‍රීක්, සිරිලික්, සිංහල, දෙමළ වැනි භාෂා වලදී ලේඛනය සඳහා පදනම්
කරගන්නා තිරස් තනි රූල. භාෂාව වෙනස් වනවිට පාදම් රේඛාවට සාපේක්ෂව අකුරු
පිහිටුවන්නේ රේඛාවට ඉහලින්ද, ඒ මතද, ඊට පහළින්ද යන්න වෙනස් වේ. ඉන්දු ලේඛණ
ක්‍රමවලදී පාදම් රේඛාවෙන් පහලට එල්ලෙන ස්වභාවයක් නිරුපනය වේ. චීන, ජපන්,
කොරියන් ( CJK ) ලේඛණ ක්‍රම වලදී තිරස් අතට මධ්‍ය රේඛා ලෙසද පාදම් රේඛාව
භාවිතා වේ. විවිධ භාෂාවල ලේඛන එකට පෙළගස්වනවිට පාදම් රේඛා භාවිතා කළ
යුත්තේ කෙසේද යන්න BASE සහ bsln වගු වලින් පෙන්වා දෙයි.

එක්ස් උස (X-height), කැපිටල් උස (Cap-height), නැග්මකය (Ascender),
බැස්මකය (Descender) සහ ඉක්මකය (Overshoot) යටතේ ත් බලන්න.

Bézier curve or Bézier splines බෙzසියර් වක්‍රය/ බෙzසියර් අැළිය

අත්පොතෙහි බෙzසියර් වක්‍ර පිළිබඳ කොටසේ පූර්ණ විස්තරයක් දක්වා අැත.

Bi-di බයි-ඩයිරෙක්ෂනල් (ද්වි-දිශාභිමුඛ) ලේඛණ

වමේ සිට දකුණටත්, දකුණේ සිට වමටත් වන සේ ද්වි දිශාභිමුඛවම පාඨ අන්තර්ගත
වන ලේඛණ. උදාහරණ ලෙස අරාබි පාඨ උපුටා දක්වන ඉංග්‍රීසි ලේඛන පෙන්විය
හැකිය. xxx අැතිවිට මේ ලේඛණ සැකසීම තවත් සංකීර්ණ වේ. යුනිකෝඩ්
ප්‍රමිතීන්හි මෙවැනි ද්විදිශාභිමුඛ ලේඛන සැකසීම සඳහා වන අැල්ගොරිතම
අන්තර්ගත වේ.

Black letter අඳුරු යුගයේ අක්ෂර

මධ්‍යකාලීන අත්අකුරු රටා මත පදනම් වන ඕනෑම අකුරු මෝස්තර පවුලක් මෙනමින්
හැඳින්විය හැක. +
වැඩි විස්තර සඳහා ගොතික් බලන්න.

Basic Multilingual Plane ( BMP ) මූලික බහුභාෂා තලය

යුනිකෝඩ් අංකන ක්‍රමයෙහි පළමු කේත 65536 න් (16 පාදයෙන් 0x00000 සිට
0x0FFFF දක්වා) සමන්විත වන කොටස. නූතන ලෝකයේ ව්‍යවහාර වන අක්ෂර සහ
සංකේත මේ තුල අඩංගුය.

වැඩි විස්තර සඳහා;

එස්එම්පී ( SMP ) - පරිපූරක බහුභාෂා තලය ( 16 පාදයෙන් 0x10000 සිට 0x1FFFF
දක්වා )

එස්අයිපී ( SIP ) - පරිපූරක රූපාක්ෂර (දෘෂ්‍යරූප) තලය ( 16 පාදයෙන් 0x20000
සිට 0x2FFFF දක්වා )

එස්එස්පී ( SSP ) - පරිපූරක විශේෂ අර්ථ තලය ( 16 පාදයෙන් 0xE0000 සිට
0xEFFFF දක්වා )

Bold තද අකුරු/ බෝල්ඩ් අකුරු

නිතර භාවිතාවන අකුරු ශෙෙලියකි. අකුරු නිර්මාණය වී අැති ඉරිවල පළල වැඩි නිසා
 ඝනකම තද පෙනුමක් තිබේ. වෙනත් අක්ෂර පිටපත් අතර පහසුවෙන් පරිවර්තනය කළ
හැකි එල්ජීසී (LGC) මෝස්තර වර්ග කිහිපය අතරින් එකකි.

Bowl බඳුන කොටස

අක්ෂරයක බඳුනක් මෙන් රවුමට අැති කොටස.

Bopomofo බොපාෙමොෆො

පුරාණ හන් දෘෂ්‍යරූප ශාබ්දිකව පිටපත් කර ශබ්දකෝෂ ගතකිරීම සඳහා යොදාගත්
නූතන (1911 දී ) චීන මැන්ඩරින් හෝඩිය.

Boustrophedon බුස්ට්‍රොෆිඩ්න් ලේඛණ ක්‍රමය

එකම භාෂාවක් (ගොනෙකු සීසාන්නාක් මෙන්) වමේ සිට දකුණටත් දකුණේ සිට වමටත්
යන ලේඛණ දිශා දෙකම ඔස්සේම ප්‍රත්‍යාවර්ත කරමින්  ලිවීම. පුරාණ ඊශ්‍රායල
භාෂාව, මුල්කාලීන ග්‍රීක ලියවිලි සහ පුරාණ ජර්මන්/ රූනික් (Runic) භාෂාවල
භාවිතා විය. එහිදී නිරන්තරයෙන්ම දකුණේ සිට වමට විහිදෙන සංකේත වමේ සිට
දකුණට විහිදෙන සංකේතවල දර්පණ ප්‍රතිබිම්බ විය. කිසිම නූතන ලිවීමේ
ක්‍රමයක් මේ ලේඛණ ක්‍රමය භාවිතා කරන බව වාර්තා නොවේ. (තවද විවෘත
ප්‍රකාර මාදිලිය මේ සඳහා කිසිම සහයෝගයක් දක්වන්නේ නැත.)

තවදුරටත්, බයි-ඩයිරෙක්ෂනල්/ ද්වි-දිශාභිමුඛ (Bidi) ලේඛණ යටතේ ත් බලන්න.

C

Cap-height කැපිටල් උස

(පැතලි හිස් මුදුනක් සහිත කැපිටල් අයි (I) අකුරක හෝ ඊට ප්‍රතිවිරුද්ධව
වක්‍ර හිස් මුදුනක් සහිත කැපිටල් ඕ (O) අකුරක ඉහලම ලක්ෂ්‍යය ට) පාදම්
රේඛාවේ සිට මනින ඉංග්‍රීසි කැපිටල් අකුරක උස.

වැඩි විස්තර සඳහා එක්ස් උස (X-height), නැග්මකය (Ascender), බැස්මකය
(Descender), ඉක්මකය (Overshoot) සහ පාදම් රේඛාව (Baseline) යටතේ බලන්න.

CFF

SFNT වෙළුම රහිත නමුත් සුසංහිත අකුරු අාකෘතිය යටතේ ‘ඕපන්ටයිප්’ පසුවදන්
අකුරු රටාවක් ලෙස බහුලවම භාවිතා වන අකුරු අකෘතිය. ‘පසුවදන් ප්‍රකාර 2’ xxx
(PostScript Type2 charstrings) යටතේ එන නිසඟ අකුරු අාකෘතියයි.

Character අක්ෂරය

අවම වශයෙන් එක් සංකේත ඉරකින් හෝ නිරූපනය කළ හැකි වනලෙස යථාරූපණය කරන ලද
ප්ලේටොනික පරමාදර්ශී කල්පිතයක්. උදාහරණ ලෙස ඉංග්‍රීසි එස් ( S ) අකුරෙන්
පෙන්වන සංකේතය, ‘S’, ‘s’, ‘_s_’, ‘ß’ සහ දිගු-s අාදී ලෙස සංකේත රැසකින්ම
පෙන්විය හැක. මේවා එකිනෙකින් වෙනස් අක්ෂර ලෙස සැලකුම් ලබන, රූපිකව සළකන
විට එකිනෙකින් සුළු වශයෙන් වෙනස් වන, මූලික පරමාදර්ශී ස්වරූප ලෙස සලකන විට
දිගු-s හි හරාත්මක ස්වරූපයෙන් වෙනස්කමක් අැත්තේම නැති තරම් වන සංකේත වේ.

Character Set අක්ෂර එකතුව

පිළිවෙළකට සකස් නොකරන ලද අක්ෂර සමූහය

CID

අක්ෂර සහ සංකේත හඳුනාගැනීමට භාවිතාවන අංකන ක්‍රමයකි. චීන, ජපන්, කොරියන්
( CJK ) අකුරු සඳහා වන සමහර පසුවදන් ප්‍රකාර අකුරු මුහුණත් වල පිල්ලම්
නාමකරණය සඳහා නම් වෙනුවට යොදාගෙන අැති අංක.

CID-keyed font CID-කේතිත අකුරු මුහුණත

පිල්ලම් අනුක්‍රම නාමකරණයේ යෙදවීමට නම් වෙනුවට සීඅයිඩී කේතනය යොදාගන්නා
පසුවදන් අකුරු මුහුණත.

CJK චීන-ජපන්-කොරියන්

චීන, ජපන්, කොරියන් (Chinese, Japanese, Korean). මේ භාෂා තුනේ ෆොන්ට රූපික
සලකුණු අතිවිශාල ගණන්වලින් සමන්විතය. රටවල් තුනෙහිදී වෙනස් පරිණාමීය
ක්‍රියාවලීන්ට බඳුන් වුවද මේ භාෂා තුනේම ලේඛණ ක්‍රම චීන රූපාක්ෂර මත පදනම්ව
අැත. තවද තායිවානයේ සහ හොංකොං වල භාවිතා වන චීන අකුරු මුහුණත් චීන ප්‍රධාන
භූමියේ (mainland) භාවිතාවන අකුරු මුහුණත් වලින් සෑහෙන පමණකින් වෙනස් වේ.

රූපාක්ෂර ක්‍රමය හැරුණු විට ජපන් සහ කොරියන් භාෂා වල ‘උච්චාරණ ශබ්ද මත
පදනම් වූ (හෝඩියක ස්වරූපයේ) අක්ෂර එකතූන්’ (phonetic syllabaries) ද භාවිතා
වේ.

‘උච්චාරණ ශබ්ද මාත්‍රා නිරූපනය කෙරෙන සංකේත’ (syllables) 60 කින් පමණ
සමන්විත හිරගන සහ කතකන හෝඩි ජපනුන් ගේ ‘උච්චාරණය කෙරෙන හඬවල් (හඬ අගයන්)
නිරූපනය කෙරෙන සංකේත වලින් සමන්විත අකාරාදී රටා’ (syllabaries) දෙක වේ.

‘උච්චාරණ ශබ්ද මාත්‍රා නිරූපනය කෙරෙන සංකේත’ (syllables) දස-දහස් ගණනකින්
සමන්විත කොරියන් හන්ගුල් හෝඩිය කොරියානුවන්ගේ ‘උච්චාරණය කෙරෙන හඬවල් (හඬ
අගයන්) නිරූපනය කෙරෙන සංකේත වලින් සමන්විත අකාරාදී රටාව’ (syllabary) වේ.

CJKV චීන-ජපන්-කොරියන්-වියට්නාම්

චීන, ජපන්, කොරියන්, වියට්නාම් (Chinese, Japanese, Korean, Vietnamese).
මේ භාෂා හතරේ අකුරු මුහුණත් සඳහා පිලි විශාල සංඛ්‍යාවක් නිර්මාණය කළ
යුතුය.

Condensed සංඝනීකෘත ෆොන්ට

රූපික සලකුණුවල කඳ කොටස් අතර පරතර සහ රූපික සලකුණු අතර පරතර අඩුකිරීමෙන්
සකස්කර ගන්නා අකුරු මුහුණත්.

Conflicting hints විසංවාදී ඉඟි

එක් රූපික සලකුණක් සඳහා ඉඟි දෙකක් අැතිවිට එක් ඉඟියක අාරම්භක සලකුණ හෝ
අවසාන සලකුණ අනෙක් ඉඟියේ සීමාව තුල පවතී නම් විසංවාදයක් හටගනී. එවිට එ්
දෙකම එකවිට ක්‍රියාකරවිය නොහැකි විය හැක.

Counter කවුන්ටර

රූපික සලකුණක සම්පූර්ණයෙන්ම හෝ අර්ධව වටවූ කොටස. ඉංග්‍රීසියෙහි o සහ n
යන රූපික සලකුණු දෙකම කවුන්ටර සහිත එ්වා වන අතර i සහ l යන දෙකටම කවුන්ටර
නැත. තවද B අකුරට කවුන්ටර දෙකක් තිබේ.

D

Descender බැස්මකය

පාදම් රේඛාවෙන් පහලට යන සිම්පල් ඉංග්‍රීසි අකුරක අකුරු කඳ කොටස. ‘p’
අකුරට බැස්මකයක් තිබේ.

වැඩි විස්තර සඳහා ‘X’ උස (X-height), කැපිටල් උස (Cap-height), නැග්මකය
(Ascender), ඉක්මකය (Overshoot) සහ පාදම් රේඛාව (Baseline) යටතේ බලන්න.

Descent බැස්ම

සාම්ප්‍රදායික මුද්‍රණාක්ෂර ශිල්පයේදී අැමිණූ අච්චු අකුරු කට්ටයක යට දාරය
සහ පාදම් රේඛාව අතර අැති දුර හැඳින්වූ නම.

නූතන පරිගණක අාශ්‍රිත අකුරු රූප ශිල්පයේදී මේ තේරුමේ නිශ්චිත බව දුරස්
වී අැත.

Device Table උපාය වගුව

පරතර සීරුමාරු කිරීම සඳහා වන විධාන අැතුලත්කිරීමට අවසර දෙන, වෛශෙෂික
පික්සල් ප්‍රමාණ වලදී පමණක් පික්සල් බවට හැරවීම සිදුකිරීම සඳහා වන කේතයන්
භාවිතා කරන අාකාරයේ විවෘත ප්‍රකාර මාදිලිය සඳහා වන පරිගණක ක්‍රමලේඛ
සංකල්පයක්. යම්කිසි ෆොන්ටයක් සලකන විට, එහි කටයුතු සඳහා සාමාන්‍ය වශයෙන්
යොදාගැනෙන යම් ක(ර්)නින් අගයක් (kerning value) පික්සල් 12 ප්‍රමාණයේ රූපික
සලකුණු සඳහා යොදාගත්විට අවලස්සන ස්වරූපයක් ගෙනදෙන්නේ නම් පික්සල් 12
ප්‍රමාණයේ (සහ අවශ්‍ය නම් පික්සල් 14 ප්‍රමාණයේ නැතහොත් පික්සල් 18, 24 හෝ
150 ප්‍රමාණයේ) පරතර සඳහා පමණක් අදාලවන යම්කිසි ශෝධනයක් එක් කළහැක.
නැංගුරම් යෙදූ සලකුණු (anchored marks) සඳහාද මෙවැනිම උපයෝගීතාවයක්
යොදාගැනීම අවශ්‍ය වේ.

Diacritics උච්චාරණ සලකුණු

අකුරක උඩින්, යටින් හෝ අකුර හරහා යන සලකුණක් ලෙස බොහෝ භාෂාවල භාවිතා
වන මෙවැනි සලකුණු උච්චාරණ සලකුණු නම්වේ. සමහර අවස්ථාවල මේවා උච්චාරණ විධි
(Accents) ලෙසද හඳුන්වන නමුත් එය වැරදි සහිත යෙදුමකි. මෙවැනි අකුරු සඳහා
උදාහරණ ලෙස À à å Å Ü ü Ø ø Ç ç වැනි අක්ෂර පෙන්විය හැකිය.

Didot point ඩිඩො(ට්) පොයින්ට්

මිලි මීටර 23.566 කට පොයින්ට් 62 ^2^/~3~ (මිලි මීටරයට පොයින්ට් 2.66 ක් හෝ
අඟලට පොයින්ට් 67.55) ක් වන යුරෝපීය පොයින්ට් අගය. මිලිමීටර 0.4 ක
ප්‍රමාණයෙන් යුතු මෙට්‍රික් ඩිඩොට් පොයින්ට් නම් අගයක් අැත.

Distortable font විපරීත කළහැකි ෆොන්ට

බහුවිධ පාලක ෆොන්ට (Multiple Master Font) යටතේ බලන්න.

E

em එම්

දිග මනින එ්කකයකි. ඔ්නෑම ෆොන්ටයක් එහි පොයින්ට් අගයට සමාන em අගයකින්
යුතුය. එනම් පොයින්ට් 10 ක ෆොන්ටයක් යනු එම් (em) 10 ක් වන ෆොන්ටයකි. එම්
ඉඩ (em-space) ක් යනු පොයින්ට් එකක පළලින් යුතු හිස් සුදු අවකාශය
(white-space) කි. එම් (හරස්) රේඛාවක් (em-dash) යනු පොයින්ට් එකක පළලින්
යුතු තිරස් රේඛාවකි.

එම් සමචතුරස්‍රයක් යනු එම් එකක දිගකින් සහ එම් එකක පළලින් යුතු
සමචතුරස්‍රයකි. (මුද්‍රණ අකුරු ලෝහයෙන් නිර්මාණය කෙරුණු) සාම්ප්‍රදායික
මුද්‍රණඅක්ෂර විද්‍යාවේදී රූපික සලකුණු එම සමචතුරස්‍රයක් තුල නිර්මාණය කළ
යුතුවිය.

em unit එම් යුනිට

ප්‍රමාණය වෙනස් කළහැකි ෆොන්ටවලදී ‘em’ ඊට වඩා කුඩා කොටස්වලට බෙදේ. පසුවදන්
ප්‍රකාර මාදිලියේදී සාමාන්‍යයෙන් em එකක් යුනිට 1000 කට බෙදෙන අතර සත්‍ය
ප්‍රකාර මාදිලියේදී em එකකට යුනිට 512 ක් 1024 ක් හෝ 2048 ක් යෙදෙන සේ
බෙදනු ලැබේ. ඉකරස් (Ikarus) ෆොන්ටවලදී em එකකට යුනිට 15000 ක් යෙදෙන සේ
බෙදනු ලැබේ. ෆොන්ට් ෆෝර්ජ් තම ඛණ්ඩාංක පද්ධතිය සඳහා මූලික එ්කකය ලෙස එම්
යුනිටය (em unit) භාවිතා කරයි.

en එන්

එම් (em) එකකින් භාගයකි.

Encoding කේතීකරණය

බයිට් (Byte) ලෙස අැති දත්ත කට්ටලයක් අක්ෂර කට්ටලයක් බවට අනුරූපණය කිරීම.
කුමන බයිට් අනුක්‍රමය කුමන අක්ෂරය නිරූපණය කරන්නේද යන්න නිර්ණය කෙරෙන්නේ
කේතීකරණ ක්‍රියාවලියේදීය. කේතීකරණය සහ අක්ෂර කට්ටලය (character set) යන
වදන් නිරන්තරයෙන් සමාන පද ලෙස භාවිතා වේ. අැස්කි (ASCII) සඳහා වන
පිරිවිතරයන් වලදී අක්ෂර කට්ටල සහ එ්වා කේතීයකරණය කරනුයේ කෙලෙසකද යන්න
නිර්ණය කරනු ලැබේ. නමුත් CJK අක්ෂර කට්ටල සලකන විට එක් කට්ටලයක් සඳහා
බහුවිධ කේතීකරණයන් තිබීම සුලභය (එමෙන්ම සමහර කේතීකරණයක් සඳහා බහුවිධ
අක්ෂර කට්ටල ද තිබේ).

වඩා සංකීර්ණ අවස්ථා වලදී එක් අක්ෂරයක් සඳහා රූපික සලකුණු කිහිපයක්ම හමුවන
අවස්ථා තිබිය හැක. (උදාහරණ ලෙස අරාබි භාෂාවේ බොහෝ අක්ෂර සඳහා අවම
වශයෙන් රූපික සලකුණු හතර බැගින් තිබේ.) එවැනි විටදී ක්‍රියාත්මකව පවතින
ක්‍රමලේඛය මඟින් එම මොහොතේ සංදර්භයට අදාලවන රූපික සලකුණ තෝරාගත
යුතුය.

Eth -- Edh

ඉංග්‍රීසි ‘th’ ශබ්දය (‘this’ වචනයේ ‘th’ ශබ්දවන ස්වරූපය -- බොහෝ
ඉංග්‍රීසි කතාකරන්නන් නොදන්නා නමුත් ඉංග්‍රීසි ‘th’ ශබ්දය ශබ්ද දෙකක
එකතුවකින් සෑදුනකි.) ට අනුරූපව යෙදුනු පුරාණ ජර්මන් බසෙහි ශබ්දය ට අදාල ‘ð’
අකුර.

Thorn යටතේත් බලන්න.

Even-Odd Fill rule ඉරට්ටේ-ඔත්තේ පිරවීමේ නීතිය

මේ නීතිය යටතේ පික්සලයක් පිරවිය යතුදැයි දැනගැනීමට, පික්සලයේ සිට ඔ්නෑම
දිශාවකට අනන්තය දක්වා විහිදෙන සරල රේඛාවක් අැඳ රේඛාවෙන් අකුරේ පිටත
මායිම කැපෙන වාර ගණන ගැණගන්න. ලැබෙන අගය ඔත්තේ නම් පික්සලය පුරවන්න.
ඉරට්ටේ නම් හිස්ව තබන්න. පසුවදන් ප්‍රකාර මාදිලියේ (දෙවන සංස්කරණයෙන්
(Version 2.0) පසුව නිකුත් කළ) අකුරු මුහුණත් පික්සල් බවට හැරවීම සඳහා වන
මෘදුකාංග වල මෙම ක්‍රමය භාවිතා වේ.

ශුන්‍ය නොවන එතුම් අංක පිරවීමේ නීතිය යටතේත් බලන්න.

Extended විස්තීරිත ෆොන්ට

රූපික සලකුණුවල කඳවල් අතර පරතරත් රූපික සලකුණු අතර පරතරත් වැඩිකිරීම මඟින්
සකස් කරගන්නා අකුරු මුහුණත්.

Extremum (__plural: __Extrema) අත්‍යන්තය

ගණිතමය වක්‍රයක් එහි උපරිම හෝ අවම අගය ලබාගන්නා ලක්ෂ්‍යය. අඛණ්ඩව ගලායන
වක්‍රයක් සලකන විට මෙවැනි ලක්ෂ එම වක්‍රයේ අාන්තීයව (උදාසීන අන්ත) සහ
dx/dt=0 හෝ dy/dt=0 වන ස්ථානවල පිහිටයි.

අකුරු මුහුණත් නිර්මාණකරණයේදී රූපික සලකුණක අත්‍යන්තයන් යනුවෙන්
හඳුන්වන්නේ රූපික සලකුණේ වැටිසනේ ඉහලම, පහලම පිහිටි ලක්ෂ්‍යයන් සහ
වමේම, දකුණේම පිහිටි ලක්ෂ්‍යයන් වේ. රූපික සලකුණුවල සියලු අත්‍යන්ත
වැටිසන් මත ලක්ෂ මඟින් නිරූපනය කර තිබීම එම රූපික සලකුණු භාවිතාවන අකුරු
මුහුණතකින් සැකසූ පෙළක් ප්‍රවචනය කිරීම සඳහා වන පරිගණක ශ්‍රමය අඩු කරයි.

F

Features (OpenType) විශේෂාංග (විවෘත ප්‍රකාර මාදිලිය)

සංකීර්ණත්වයෙන් වැඩි හෝඩි සඳහා (සමහර සංකීර්ණත්වයෙන් අඩු හෝඩි සඳහාත්)
අකුරු මුහුණත් නිමවන විට, රූපික සලකුණකට අදාල කේතය යතුරු පුවරුවක් මඟින්
අැතුලත් කිරීමෙන් පසු තිරයක් මත දෘෂ්‍ය කිරීම ට පෙර එම රූපික සලකුණට අදාලවන
විවිධ පරිණාමණයන් රැසක් (බැඳි අකුරු එකතුකිරීම වැනි) සිදුකළ යුතුවේ. මෙම
පරිණාමණයන් ෆොන්ට විශේෂාංග ලෙස හඳුන්වන අතර විවෘත ප්‍රකාර මාදිලියේදී අකුරු
හතරක අැමුණුමක් (4 letter tag) ලෙසත් ‘අැපල්’ මාදිලිවලදී අංක දෙකක
හඳුනනුවක් (2 number identifier) ලෙසත් යෙදේ. මෙම විශේෂාංගවලට අැති තේරුම්
මොනවාද යන්න මයික්‍රොසොෆ්ට් සහ අැපල් සමාගම් විසින් පූර්වයෙන් නිශ්චය කරනු
ලැබ අැත. ෆොන්ට් ෆෝර්ජ් භාවිතයෙන් නිර්මාණය කරන සෑම රූපික සලකුණක් පාසාම එ්
තුල අඩංගු කරනු ලබන විශේෂාංග මොනවාද යන්න තේරීමට ඉඩ සලසා අැත.

Feature File විශේෂාංග ගොනුව

විවෘත ප්‍රකාර විශේෂාංග මොනවාදැයි විස්තරකිරීමට ‘අැඩෝබි’ විසින් නිර්මාණය
කරන ලද පෙළ වින්‍යාසයකි (text syntax). විශේෂාංග සහ සෝදිසි තොරතුරු
(feature and lookup information) ෆොන්ට අතර හුවමාරු කිරීමට මෙය යොදාගත
හැකිය.

Feature/ Settings (Apple) විශේෂාංග/ සැකසුම් (අැපල්)

ඉහත සඳහන් කළ විවෘත ප්‍රකාර විශේෂාංග වලට දළ වශයෙන් සමාන වන, අැපල් විසින්
නිර්ණයනය කරන ලද සැකසුම්.

Font ෆොන්ටය/ අකුරු මුහුණත

සාමාන්‍ය තත්ව යටතේ සලකනු ලබන විට, අක්ෂර එකතුවේ එක් එක් අක්ෂරය සඳහා අවම
වශයෙන් එක් එක් රූපික සලකුණක් සංඝටිත කර අැත්තා වූත් එම රූපික සලකුණු අදාල
එ් එ් අක්ෂරය සමඟ කේතීකරණයට බඳුන් කර අැත්තාවූත් රූපික සලකුණු එකතුවක්.

තවත් අයුරකින් කියන්නේ නම්, විධානයක් ලෙස ලබාදෙන ‘බයිට්’ (byte)
අනුපිළිවෙළක් එයින් නිරූපනය කෙරෙන අක්ෂර සමුදායට අනුරූප සංකේතීය රූප පෙළක්
බවට හැරවීම සඳහා වන තොරතුරු සමුදාය අඩංගුකර අැති ගොනුවක් ෆොන්ටයකි.

සාම්ප්‍රදායික මුද්‍රණාක්ෂර විද්‍යාවේදී ෆොන්ටයක් යනු අල්ප උන්නතව කැටයම්
කරන ලද අක්ෂර වල සංකේත රූප අඩංගු කුඩා ලෝහ කුට්ටි එකතුවකි. මෙම අර්ථ
දැක්වීමට අනුව එකම මෝස්තරයේ වෙනස් ප්‍රමාණවල ලෝහ කුට්ටි එකතු වෙනස් ෆොන්ට
ලෙස සැලකිනි. එවිට සලකනු ලබන මෝස්තරයක් සඳහා පොයින්ට් ප්‍රමාණයේ තිබිය හැකි
සෑම වෙනසකටම වෙනස් ෆොන්ටයක් තිබේ.

Font Family, or Family අකුරු මුහුණත් පවුල, හෝ පවුල

එකිනෙකට අදාල ෆොන්ට එකතුවක් හඳුන්වන නම. ෆොන්ට පවුලක සෑමවිටම පාහේ එකම
මෝස්තරයේ සාමාන්‍ය, ඉටැලික් සහ බෝල්ඩ් විලාසයන් අන්තර්ගත වේ.

FreeType නිදහස් ප්‍රකාර

අකුරු මුහුණත් මොනිටර තිරය මත පික්සල් පාදකව සංදර්ශනය කිරීම
(rasterization) සඳහා යොදාගන්නා සම්මත ක්‍රමලේඛ සහ උප-නෙෙත්‍යක
(sub-routine) සංග්‍රහය. ෆොන්ට් ෆෝර්ජ් සමඟ සත්‍ය-ප්‍රකාර අකුරු මුහුණත්
වල හැසිරීම තේරුම්ගැනීම සඳහා සහ ෆොන්ට් ෆෝර්ජ් තනිවම කරනවාට වඩා
ශක්‍යතාවයකින් යුතුව මොනිටර තිරය මත පික්සල් පාදක සංදර්ශනය ඉටු කරවාගැනීමට
විපුල වශයෙන් භාවිතා වේ.

Fuþark (Futhark) ෆුතාර්ක් හෝඩිය

පුරාණ ජර්මන්, රූනික් (Runic) අක්ෂර මාලාව.

G

Ghost Hint භූත ඉඟිය

සමහර අවස්ථාවල තිරස් මුල්ලක් නිසැකයෙන්ම තිරස් බව පෙන්වීම වැදගත් වේ.
නමුත් සාමාන්‍ය පරිදි අැණියකට අනුරූප කර පෙන්වීම සඳහා විශිෂ්ට ලෙස භාවිතා
කළ හැකි මුල්ලක් විශද නොවේ නම් පළල -20 (හෝ -21) කින් යුතු විශේෂ
ඉඟියක් භාවිතා කළ යුතුය. භූත ඉඟියක් අනිවාර්්‍යයෙන්ම මුලුමනින්ම රූපික
සළකුණක් තුල අන්තර්ගත කළ හැකිවිය යුතුය. මුල්ල බාහිර හැඩයේ (contour) ඉහල
පිහිටියේ නම් -20 ක පළල ද මුල්ල බාහිර හැඩයේ පහළ පිහිටියේ නම් -21 ක පළල
ද භාවිතා කරන්න. භූත ඉඟි සෑමවිටම ‘නිල් කලාප’ (Blue Zones) තුල පිහිටුවීම
වඩාත් සුදුසුය.

(භූත ඉඟි සැකසීම සඳහා වන ‘පිරිවිතර නියමාවලිය’ (spec/ specification) සිරස්
භූත ඉඟි ගැනද සඳහන් කරයි. නමුත් සිරස් නිල් කලාප යනුවෙන් දෙයක් නොමැති නිසා
සිරස් භූත ඉඟි භාවිතා කළ යුත්තේ කෙලෙසදැයි යන්න පැහැදිලි නැත.)

Glyph රූපික සළකුණ

රූපික සළකුණක් යනු සෑමවිටම පාහේ අක්ෂර එකක් හෝ කිහිපයක් සමඟ සංඝටිත කළ
බලියකි. “ f ” ලෙස අඳිනු ලබන රූපික සළකුණ (බලිය) f අකුර සමඟ සංඝටිත වී අැති
අතර “ fi ” ලෙස අඳිනු ලබන බැඳි අකුරේ රූපික සළකුණ (බලිය) f සහ i අකුරු
දෙකම සමඟ සංඝටිත වී අැත. සරල ලතින් ෆොන්ටවල දී සංඝටනය නිරන්තරයෙන්
එකකට-එකක් (සෑම අක්ෂරයකටම නිශ්චිත එක් රූපික සලකුණක් පමණක්) වන පරිදි
සිදුවන අතර වඩා සංකීර්ණ ෆොන්ට හෝ අක්ෂරමාලා වලදී එක් අක්ෂරයක් සඳහා රූපික
සලකුණු කිහිපයක්ම තිබිය හැකිය. (පුනරුද සමයේ මුද්‍රණ කටයුතු වලදී ඉංග්‍රීසි
එස් (s) අකුර හා බැඳි රූපික සලකුණු දෙකක් තිබිණි. එයින් එකක් වූ දිග එස්
(long-s) අකුර වචනයක අාරම්භයේදී සහ අවසානයේදී භාවිතා වූ අතර අනෙක වූ කෙටි
එස් (short-s) අකුර වචනයක අවසානයේදී පමණක් යොදන ලදී.) බැඳි අකුරු වලදී එක්
රූපික සලකුණක් අක්ෂර දෙකක් හෝ ඊට වැඩි ගණනක් සමඟ සංඝටිත වී තිබේ.

අකුරු මුහුණත් (ෆොන්ට) යනු, යථාරූපණය කරන ලද ප්ලේටොනික පරමාදර්ශී කල්පිත
එ් සමඟ යම් අයුරක අනුරූපණයක් පෙන්වන රූපික සළකුණු (බලි) ලෙස අැතිවිට එ්
රූපික සළකුණුවල ස්වරූපය යම් යම් රටාවන්ට සැකසීමෙන් ලබාගන්නා විවිධාකාර
රූපික සළකුණු සමුච්චයන් වේ.

Grid Fitting ජාලක අනුසීහුම

සත්‍ය ප්‍රකාර රූපික සළකුණු පික්සල් අාකාරයෙන් තිරයක් මත දෘෂ්‍ය කිරීමට පෙර
එ්වා ජාලක අනුසීහුම නම් ක්‍රියාවලියකට බඳුන් කළ යුතුවේ. එහිදී සෑම රූපික
සළකුණකම වැටිසන මත අැති නැංගුරම් ලක්ෂ රූපික සළකුණට අදාල, ඊටම බැඳුණු
ක්ෂුද්‍ර ක්‍රමලේඛ මඟින් පික්සල් ජාලය මත එහා මෙහා කිරීමෙන් තිරය මත වඩාත්
හොඳින් දෘෂ්‍ය කරවිය හැකි පිහිටුමක් ලබාගනු ලැබේ.

Gothic ගොතික්

ගුටෙන්බර්ග් (ව්‍යවහාර වර්ෂ 1400-1468 අතර ජර්මනියේ නිශ්පාදනය වූ මුද්‍රණ
යන්ත්‍රයකි. පළමුවරට සචල මුද්‍රණ තාක්ෂණය සහිත වීම නිසා පළමුවරට යුරෝපයේ
මුද්‍රණාලයක භාවිතා විය.) යුගයේ ජර්මන් පූජකවරුන්ගේ ‘කළු අකුරු’
(black-letter) ලිවීමේ කලාව. ගුටෙන්බර්ග් මුද්‍රකයේ නිශ්පාදක ජොහැන්නස්
ගුටෙන්බර්ග් විසින් එම කළු අකුරු කලාව ඔහුගේ මුද්‍රණ යන්ත්‍රයෙහි අඩංගු
කරන ලදී. මුද්‍රණ තාක්ෂණය යුරෝපයේ දකුණු දිගට ව්‍යාප්ත වීමෙන් පසු මේ
අකුරු රටාව ඉතාලි මුද්‍රණ යන්ත්‍ර අකුරු සැළසුම්කරුවන්ගේ අවඥාවට බඳුන් වූ
අතර ඔවුහු එම අකුරු පැරණි රෝම අකුරු වලින් ප්‍රතිෂ්ඨාපනය කරමින් ව්‍යවහාර
වර්ෂයෙන් 3-5 සියවස් අතර රෝම අධිරාජ්‍යය විනාශ කිරීමට දායක වූ ජර්මනිය
අාශ්‍රිත ‘ගොත්’ ජනයාගේ නමින් අාභාෂය ගෙන මේ ජර්මන් අකුරු රටාව සිනහවට
ලක් කළහ.

Gaphite tables ග්‍රැෆයිට් වගු

සංදර්භානුගත හැඩගෑම (Contextual Shaping), බැඳි අකුරු (Ligatures), පුනර්
පටිපාටිගත කිරීම (Reordering), විභේදිත රූපික සළකුණු (Split Glyphs), ද්වි
දිශාභිමුඛත්වය (Bidirectionality), උච්චාරණ සලකුණු අැසිරීම (Stacking
Diacritics), සංකීර්ණ පිහිටුවීම් (Complex Positioning) අාදී කටයුතු සඳහා
වන කොන්දේසි අඩංගු වගු අකුරු මුහුණතකට එබ්බවීම සඳහා භාවිතාවන සත්‍ය
ප්‍රකාර මාදිලිය සඳහා වන දිගුවක් (extension).

මෙය තරමක් දුරට විවෘත ප්‍රකාර මාදිලියේ ක්‍රියාකාරීත්වයට සමාන සෙයක් හැඟී
යා හැකි වුවත් ඊට වෙනස්ව විවෘත ප්‍රකාර මාදිලිය එ් තුල අන්තර්ගත වන රූපික
සලකුණු පිළිබඳව වන විශාල අවබෝධයක් සහිතව පෙළ වින්‍යාස සැලැස්මේ රූටින (text
layout routines) මත යැපේ. එහෙයින් නව භාෂාවක් හෝ හෝඩියක් සඳහා විවෘත
ප්‍රකාර මාදිලියේ ෆොන්ට නිර්මාණය කිරීම මෙහෙයුම් පද්ධතියේ නව සංස්කරණයක්
නිකුත් කිරීමකින් තොරව කළ නොහැකිය. එනමුත් ඊට වෙනස් ලෙස ග්‍රැෆයිට් වගුවල
සියලුම සඟවන ලද තොරතුරු අඩංගු වේ.

‘ඇපල්’ වර්ධිත අක්ෂර මේ කටයුත්ත කරගැනීම සඳහා වඩාත් හොඳ මට්ටමේ තරඟකරුවකු
සැපයුවද ග්‍රැෆයිට් වගු ගොඩනැංවීමට අැති පහසුව නිරන්තරයෙන් පුනරුච්චාරණය වන
කරුණකි.

ජාත්‍යන්තර SIL (SIL International) අායතනය නිදහස් ග්‍රැෆයිට් සම්පාදකයක්
නිශ්පාදනය කරයි.

Grotesques විකෘතරූප

‘සාන්ස් සෙරීෆ්’ (Sans Serif) යටතේ බලන්න.

H

Han characters ‘හන්’ අකුරු

චීන, ජපන් සහ කොරියන් (වියට්නාමය අාදී තවත් අාසියානු රටවලත්) රටවල
භාවිතාවන චීනයේ පරිණාමය වූ ලේඛණ කලාව පදනම් කරගත් රූපාක්ෂර ලේඛණ කලාව.

[චීන හන් යුගය ගැනත් ලියන්න]

Hangul හන්ගුල්

කොරියන් අක්ෂරමාලාව (Korean syllabary) ට කියන නම. දන්නා තරමින් හෝඩියක්
(alphabet) මත පදනම් වූ එකම අක්ෂර මාලාව (syllabary) මෙය වේ. මෙම හෝඩියේ
අකුරු කිසිම විටෙක තනි තනිව ප්‍රකාශයට පත් වන්නේ නැති අතර අකුරු දෙකක හෝ
තුනක ක‍ණ්ඩායම් වශයෙන් මාත්‍රාවන් ලෙස ප්‍රකාශයට පත්වේ.

Hanja හන්ජා

‘හන්’ අකුරු වලට කියන කොරියන් නම

Hints ඉඟි

කුඩා පොයින්ට් ප්‍රමාණ සඳහා වන රූපික සලකුණු වඩාත් හොඳින් අැඳිමට
රාස්ටරයිසරයට උදව් කරයි. ප්‍රධාන මැනුවලයෙහි මේවා සවිස්තර වශයෙන් දක්වා
අැත.

Hint Masks ඉඟි අාවරණක

බාහිර හැඩයේ දෙන ලද ඔ්නෑම ලක්ෂ්‍යයක් සඳහා ඉඟි සංඝටනයක් සිදු නොවිය
යුතුය. නමුත් රූපික සලකුණක අැති වෙනස් ලක්ෂ්‍යයන් සමහරකට සංඝටන සහිත ඉඟි
අවශ්‍ය විය හැකිය. එහෙයින් අවශ්‍යවන සෑමවිටම පාහේ බාහිර හැඩය විසින්
ක්‍රියාකාරීත්වයේ පවතින ඉඟි මොනවාද යන්න වෙනස් කෙරේ. මෙම සෑම
ක්‍රියාකාරී ඉඟි ලැයිස්තුවක්ම ඉඟි අාවරණකයක් ලෙස හැඳින්වේ.

Hiragana හිරගන

ජපන් හෝඩි (අකුරු එකතු) දෙකින් එකකි. හිරගන සහ කතකන (Katakana) හෝඩි
දෙකම එකම ශබ්ද එකතුවක් නිරූපනය කරයි.

I

Ideographic character රූපාක්ෂරය

ශාබ්දික උච්චාරණයකින් තොරව සංකල්පීය අදහසක් නිරූපණය කළහැකි තනි අක්ෂරයක්.
(චීන) හන් අකුරු හැඳින්වීම සඳහා සාමාන්‍යයෙන් යොදන යෙදුමකි.

Italic ඉටැලික්/ අැල අකුරු

බර කොට කියන බව, විශේෂ වශයෙන් කියන බව හැඟවීම සඳහා නිරන්තරයෙන් භාවිතා
වන, අක්ෂර ඉහලින් දකුණු පැත්තට අැල කරන ලද ස්වභාවයෙන් යුතු ශෙෙලිය.

අැලකිරීමේදී අක්ෂර පමණක් අැලකරනවාද නැතහොත් අක්ෂර හා සබැඳි අනෙක් අංගෝපාංග
වලටත් අදාලව අැලකිරීම සිදුකරනවාද යන්න මත ඉටැලික් අැලකිරීම ඔබ්ලික්
අැලකිරීමෙන් වෙනස් වේ. සාමාන්‍යයෙන් ‘a’ (සිම්පල් එ්) අකුර ‘_a_’ බවට
වෙනස්වන අතර ‘i’ (සිම්පල් අයි) අකුර වැනි සිම්පල් අකුරුවල අැති සෙරීෆ්
කොටස් වෙනස් ස්වරූප (_‘i’_) බවට හැරේ. සමස්තයක් වශයෙන් ෆොන්ටය වඩාත් ගලායන
රිත්මයක් ලබාගනී.

J

Jamo ජමෝ

කොරියන් හෝඩියේ අක්ෂර. භාවිතයේදී මේවා කිසිසේත්ම තනි තනිව දකින්නට නොලැබෙන
අතර බොහෝවිට අක්ෂර තුනේ කාණ්ඩ වශයෙන් හන්ගුල් මාත්‍රාවක කොටසක් ලෙස දකින්නට
ලැබේ. Choseong (අාරම්භක ව්‍යංජනාක්ෂර), Jungseong (මධ්‍යයීය ස්වර) සහ
Jongseong (අවසාන ව්‍යංජනාක්ෂර) ලෙස ජමෝ අක්ෂර කාණ්ඩ තුනකට (පළමු සහ තෙවන
කාණ්ඩ අතර සැලකිය යුතු තරමේ අතිච්ඡාදනයක් සහිත වුවත්) බෙදනු ලැබේ. ‘එම්
සමචතුරස්‍රය’ (em-square) ක ඉහල වම් කෙළවරේ Choseong රූපික සලකුණකුත් ඉහල
දකුණු කෙළවරේ Jungseong රූපික සලකුණකුත් චතුරස්‍රයේ පහල කොටසේ (අතිරේක)
Jongseong රූපික සලකුණකුත් ස්ථානගත කිරීමෙන් මාත්‍රාවක් සංරචනය කරනු ලැබේ.

K

Kanji කන්ජි

හන් අකුරු වලට කියන ජපන් නම.

Katakana කතකන

(නූතන) ජපන් අක්ෂරමාලා දෙකින් එකක්. කතකන සහ හිරගන යන අක්ෂරමාලා දෙකෙහිම
අැත්තේ එකම ශබ්ද මාලාවකි.

Kerning ක(ර්)නින්

රූපික සලකුණු දෙකක් අතර පරතරය පෙර සැකසූ අගයක තබාගැනීම ෆොන්ටයේ සමස්ත
වින්‍යාසය හා දෘෂ්‍යමය වශයෙන් නොගැලපෙන විට ෆොන්ටයෙහි අන්තර්ගත කෙරෙන
අතිරේක තොරතුරු සමුදායක උදවුවෙන් එම අගය අදාල අවස්ථාවට ගැලපෙන පරිදි
සකසාගැනීමට හැකිය. උදාහරණ වශයෙන් දෙන ලද අකුරකට (‘T’ යැයි කියමු) පසුව තවත්
අකුරක් (‘o’ යැයි කියමු) යෙදෙන විට ‘T’ හි වර්ධිත පළල (Advanced Width) යම්
අගයකින් අලුතින් ගැලපීමෙන් අතුරු මුහුණතේ වඩාත් මනෝඥ දෘෂ්‍ය රූපයක් තනාගත
හැකිය.

ලෝහ අකුරු මුහුණත් වලින් මුද්‍රණය කරන කාලයේ අකුරු දෙකක් අතර පරතරය
සැකසීමට භාවිතාවන පතුරු පීරිගෑමෙන් වඩාත් කිට්ටුවෙන් අැසිරුණු පෙනුමක් අැති
අකුරු සැකැස්මක් ලබාගන්නා ලදී. උදාහරණයක් වශයෙන් ‘F’ අකුරට පසුව තවත්
අකුරක් අැතිවිට ‘F’ අකුරේ දකුණුපසින් යම් ලෝහ ප්‍රමාණයක් ඉවත් කිරීම
හරහා ඊට පසුව එන සිම්පල් අකුර ‘F’ අකුරට වඩාත් කිට්ටුකිරීමෙන් අකුරු
සැකැස්මේ දර්ශනීයත්වය වැඩිකරගත හැක.

Kern pair ක(ර්)න් පෙයා(ර්)

ක(ර්)නින් පිරිවිතර නිර්ණය කර අැති රූපික මුහුණත් යුගලයක්.

Kerning by classes පංති අනුව ක(ර්)න් කිරීම

අකුරු මුහුණතක අැති රූපික මුහුණත් සියල්ල රූපික මුහුණත් පංති වශයෙන් බෙදා
එවැනි පංති අතර අැතිවිය හැකි සියලු සංයෝජනයන් සඳහා වන ක(ර්)නින්
පිරිවිතරයන් අඩංගු විශාල වගුවක් සකසනු ලැබේ. එක් පංතියක් තුල සාමාන්‍යයෙන්
ක(ර්)න් පෙයා(ර්) එකකට වැඩි ගණනක් අඩංගුවන හෙයින් මෙවැනි වගුවක් සැකසීම
මඟින් ක(ර්)න් පෙයාර් යුගල අඩංගු වගුවක අැති දත්ත ප්‍රමාණයට වඩා අඩු දත්ත
ප්‍රමාණයක් මඟින් ක(ර්)නින් ක්‍රියාවලිය ඉටුකරගත හැක.

Knuth,Donald ඩොනල්ඩ් ක්නූත්

1970 සහ 80 කාලයේ තමා ජීවත් වූ සමාජ පරිසරයේ සැරිසැරූ වැරදි සහිත අකුරු
මුහුණත් සැකසුම් වලින් විඩාවට පත්වී MetaFont සහ TeX යන නම්වලින් ෆොන්ට්
නිර්මාණ ක්‍රමවේදයක් සහ අකුරු මුහුණත් සැලසුම් කළහැකි ක්‍රමලේඛයක්
නිර්මාණය කළ ගණිතඥයෙකි.

L

Left side bearing වමත් පස බෙයාරිම

රූපික සලකුණක අැරඹුම් ලක්ෂ්‍යයේ සිට එහි වමින්ම පිහිටා අැති ලක්ෂ්‍යයට
අැති තිරස් දුර. මෙම අගය (-) හෝ (+) අගයක් විය හැක.

Lemur ලෙමූ(ර්)

වර්තමානයේ මැඩගස්කරයේ පමණක් දක්නට ලැබෙන නමුත් වසර මිලියන 50 කට පමණ
පෙරදී පොළව මත විශාල ප්‍රදේශයක ජීවත්වූ විශාල අැස් සහ කන් සහිත, නිශාචර
ජීවිත ගතකළ ප්‍රාථමික ප්‍රයිමේටාවන් ගෙන් යුතු එ්කදර්ශී ජනුවක්. (A
monotypic genus of prosimian primates)

Ligature බැඳි අකුරු

යාබදව පිහිටන රූපික සලකුණු දෙකක් එකට බන්දා තනි රූපික සලකුණක් පැනෙන සේ
කරන සැකසීම. නිතර සඳහන්වන උදාහරණයක් ලෙස ලතින් ලේඛනයේදී ‘f’ සහ ‘i’ අකුරු
බැන්දීමෙන් තනි තනි අකුරු ලෙස තිබෙනවාට වඩා හැඩැති ‘fi’ බැඳි අකුර ලබාගැනීම
පෙන්විය හැක.

Linespace පේලි පරතරය

අනුයාත අකුරු පේලි දෙකක් අතර පරතරය.

LGC ලතින්-ග්‍රීක්-සිරිලික්

ලතින්, ග්‍රීක්, සිරිලික්. පසුගිය සහස්‍ර කිහිපය පුරාවටම එකිනෙකා අතර
සහසම්බන්ධීව පරිණාමය වූ අකුරු මුහුණත් තුනක්. මේවායේ අක්ෂර හැඩතල බොහෝ
සමානකම් දක්වන අතර (සමහර අක්ෂර හවුලේ භාවිතා වේ) ‘සිම්පල් අකුරු’,
‘ඉටැලික් අකුරු’ වැනි වෙනත් කිසිම බසක නොයෙදෙන අකුරු මුහුණත් සම්බන්ධ
බොහෝ සංකල්ප මේ තුනෙහිම එකලෙස යෙදේ. (ව්‍යතිරේකයක් ලෙස;
අා(ර්)මේනියන් බසෙහි සිම්පල් අකුරු තිබේ)

M

Manyogana මන්යෝගන

හිරගන සහ කතකන අක්ෂරමාලා දෙකටම මඟපෑදූ මුල්කාලීන ජපන් අක්ෂරමාලාව.
මන්යෝගන අක්ෂරමාලාව තම උච්චාරණ ශබ්ද සඳහා රූපික ස්වරූපයන් ලබාගෙන අැත්තේ
කන්ජි අකුරු වලින් වන අතර කාලානුරූප පරිණාමනයෙන් මෙම අකුරු හිරගන සහ කතකන
බවට සරල වී අැත.

Monospace එ්ක-අවකාශ ෆොන්ට/ එකම-ඉඩ ෆොන්ට

සෑම රූපික සලකුණකම පළල එකම වනසේ නිර්මාණය කළ අකුරු මුහුණත්. සමහර
අවස්ථාවලදී ‘යතුරු ලියන ෆොන්ට’ ලෙසද හඳුන්වයි.

Multi-layered fonts බහු ස්තර ෆොන්ට

(ෆොන්ට් ෆෝර්ජ් විසින් හඳුන්වාදුන් යෙදුමකි) පසුවදන් ප්‍රකාර මාදිලියේ
තෙවැනි (PostScript type3) අාකාරයේ සහ SVG අාකාරයේ ෆොන්ට එ්වා නිර්මාණය
වී අැති ගුණාංග වෙනස් කිරීම මඟින් සාමාන්‍ය ෆොන්ට වලට වඩා වැඩි අාකාර
ගණනකින් අැඳීමේ හැකියාව තිබේ. සාමාන්‍ය ෆොන්ට බොහෝවිට සහයෝගය
දක්වන්නේ ග්‍රාෆික පරිස්ථිතිය (graphics environment) තුල අන්තර්ගත තනි
තනි වර්ණ පිරවීම සඳහා පමණි. නමුත් ඉහත ෆොන්ට අාකාර දෙක නොයෙක් වෙනස්
වර්ණයෙන් පිරවීම (filled with several different colors), පින්සල් පහර
එක්කිරීම (stroked), රූප පිළිබිඹු එක්කිරීම (include images), වර්ණ
අනුක්‍රමණ අැතිකිරීම (have gradient fills) අාදී කටයුතු රැසක් සඳහා
සහයෝගය දක්වයි. රැම් මතකයේ (RAM Memory) විශාල ඉඩක් අත්කරගන්නා හෙයින්
මෙම පහසුකම සඳහා වන සැකැස්ම ෆොන්ට් ෆෝර්ජ් හි පෙර සැකසූ සැකැස්මක් ලෙස
නොපැමිණේ. නමුත් ඉහත ෆොන්ට වලට සහයෝගය දැක්වීම අවශ්‍ය වන විට ඊට අදාල
විධානයන් සිදුකිරීම මඟින් ෆොන්ට් ෆෝර්ජ් හි අදාල සහයෝගීතාවය පහසුවෙන්
ලබාගත හැකිය.

Multiple Master Font බහුවිධ පාලක ෆොන්ට

අාශ්‍රිත අදාල ෆොන්ට අනන්ත සංඛ්‍යාවක් අර්ථ දැක්වෙන සේ නිමවූ පසුවදන්
ප්‍රකාර මාදිලියේ ෆොන්ට පරිපාටියකි. බහුවිධ පාලක ෆොන්ට, අක්ෂ බොහෝ
ගණනක් ඔස්සේ යාහැකි විවිධත්වයන් සහිත එ්වා වේ. උදාහරණයක් ලෙස ෆොන්ට
පවුලක් සඳහා දෘෂ්‍ය බරවල් අතර වෙනස්කම් (different weights) සහ පළලවල් අතර
වෙනස්කම් (different widths) යන කරුණු දෙකම අර්ථ දැක්වීම සඳහා බහුවිධ
පාලකයක් සැකසීම මඟින් හීන් (Thin), සාමාන්‍ය (Normal), අර්ධ තද
(Semi-Bold), තද (Bold), සංඝනීකෘත (Condensed), ප්‍රසාරිත (Expanded), තද
සංඝනීකෘත (Bold-Condensed) අාදී මෝස්තර මාදිලි රැසක් ජනනය කරගත හැකිය.

අැඩෝබි තවදුරටත් මේ අාකෘතිය දියුණුකිරීම නවතාදමා අැත. අැපල් සතුව මෙම
කටයුත්තම කරන වෙනත් අාකෘතියක් අැති අතර එමඟින් එතරම් විශාල වැඩකොටසක්
ඉටුකර නැත. ෆොන්ට් ෆෝර්ජ් එම අාකෘති දෙක සඳහාම සහයෝගය දක්වයි.

N

Namelist නම් ලැයිස්තුව

යුනිකෝඩ් කේත ලක්ෂ්‍යය සහ රූපාක්ෂරයේ නම අතර අැති අනුරූපණය.

Non-Zero Winding Number Fill rule ශුන්‍ය නොවන එතුම් අංක පිරවීමේ නීතිය

පික්සලයක් මේ නීතියට අනුව පිරවිය යතුදැයි නිර්ණය කිරීම සඳහා, [එතැන්] සිට
ඔනෑම දිශාවකට අනන්තය දක්වා දිවෙන සරල රේඛාවක් අැඳ එ් රේඛාවෙන් අකුරේ
පිටත මායිම කැපෙන වාර ගණන ගැණගන්න. පිටත මායිම සරල රේඛාව හරහා යන්නේ
දක්ෂිණාවර්තව නම් 1 ක් එකතුකරන්න. වාමාවර්තව නම් 1 ක් අඩුකරන්න. අවසානයේ
ලැබෙන අගය ශුන්‍යය නොවේ නම් පික්සලය පුරවන්න. ශුන්‍යය වේ නම් පික්සලය
හිස්ව තබන්න. සත්‍ය ප්‍රකාර මාදිලියේ සහ (දෙවන සංස්කරණයට වඩා) පැරණි
පසුවදන් ප්‍රකාර මාදිලියේ අකුරු මුහුණත් පික්සල් බවට හැරවීම සඳහා මේ
ක්‍රමය යොදාගැනේ.

ඉරට්ටේ-ඔත්තේ පිරවීමේ නීතිය (Even-Odd Fill Rule) ත් බලන්න.

O

Ogham ඔග්හැම්

පුරාණ සෙල්ටික් ශිලාලේඛණ අක්ෂරමාලාව.

Open-Type විවෘත-ප්‍රකාර මාදිලිය

පසුවදන් ප්‍රකාර පිරිවිතර සහ සත්‍ය-ප්‍රකාර පිරිවිතර දෙකම එකම පිරිවිතර
සමුදායක් යටතට ගෙන සැකසූ අකුරු මුහුණත් කුලකයකි.

එහෙයින් විවෘත-ප්‍රකාර මාදිලිය යටතේ එන අකුරු මුහුණතක් පසුවදන් ප්‍රකාර
මාදිලිය යටතට හෝ සත්‍ය-ප්‍රකාර මාදිලිය යටතට අදාල විය හැක.

මේ යටතේ එන කේතීකරණ තොරතුරු වගු සහ එවැනි දත්ත වගු බොහෝමයක්
සත්‍ය-ප්‍රකාර මාදිලියේ අඩංගු වන එ්වාම වේ.

සංදර්භානුගත බැඳි අකුරු, සංදර්භානුගත ක(ර්)නින් කිරීම, රූපාක්ෂර අාදේශනය
අාදී හැඩසවීම් අන්තර්ගත කර අැඩෝබි සහ මයික්‍රොසොෆ්ට් (නමුත් අැපල් අදාල
නොවේ.) සමාගම් විසින් සත්‍ය ප්‍රකාර මාදිලිය සඳහා එකතුකළ වර්ධිත
මුද්‍රණාක්ෂර වගු (advanced typographic tables) හැඳින්වීමටත් මෙම නමම
යෙදීම නිසා සමහර අවස්ථාවල මේ යෙදුම ව්‍යාකූල අරුතක් ගෙන එන්නට සමත්වේ.

මයික්‍රොසොෆ්ට් වින්ඩෝස් විසින් අංකිත මුද්‍රා වගුවක් (DSIG table
(Digital Signature table)) සහිත ෆොන්ටයක් හැඳින්වීමටද මෙම නමම යොදාගනී.

Open-Type Tables විවෘත-ප්‍රකාර වගු

සෑම විවෘත-ප්‍රකාර අකුරු මුහුණත් ගොනුවකම අඩංගු එ් හා බැඳුණු නිශ්චිත
තොරතුරු වලින් සමන්විත වන වගු.

Oblique ඔබ්ලික්/ අැල අකුරු

අවධාරණය කොට/ බරකොට කියන බව හැඟවීම සඳහා භාවිතාකරන අකුරු මෝස්තරයක අැල
ශෙෙලිය.

අක්ෂර හැඩවල සාමාන්‍ය ශෙෙලියේ සිට අැල ශෙෙලිය දක්වා වන රූපාන්තරණ
ක්‍රියාවලිය සිදුකරනුයේ ගණිතමයවද නැතහොත් යාන්ත්‍රිකවද යන්න මත ඔබ්ලික්
ඉටැලික් වලින් වෙනස් වේ.

Overshoot ඉක්මකය

ඉංග්‍රීසි කැපිටල් අයි ‘I’ අකුරේ පැතලි හිස හා සමාන උස මට්ටමින් ඉංග්‍රීසි
කැපිටල් ඔ් ‘O’ අකුරේ රවුම් හිස පවතින බව පෙන්වීමට ‘O’ අකුරේ උස කැපිටල්
උස (හෙවත් ‘x’ උස) උපරි ඉක්මවායාමක් සිදුකිරීම හෝ පාදම් රේඛාව කැපිටල්
උසින් (හෙවත් ‘x’ උසින්) 3% කින් පමණ අධහ් ඉක්මවායාමක් සිදුකිරීම අවශ්‍ය
වේ. (කැපිටල් ‘A’ වැනි) ත්‍රිකෝණාකාර හැඩ සඳහා ඉක්මකය 5% ක් පමණ දක්වා
විශාල අගයක් ගත හැක.

ඉහත මාර්ගෝපදේශනයෙහි පදනම වන්නේ අැසෙහි සංජානන ක්‍රියාදාමය සහ අැස ජනිත
කරන දෘෂ්‍ය මායාවන් පිලිබඳ දැනුමයි. අදාල විස්තර පීටර් කරෝව් ගේ අකුරු
මුහුණත් සඳහා වන අංකිත අාකෘති (Peter Karow's Digital Formats for
Typefaces) පොතෙහි 26 වන පිටුවේ සිට අැති විස්තර වලින් ලබාගෙන අැත.

ෆොන්ටයක පොයින්ට් ප්‍රමාණය මත ඉක්මකය රඳා පවතී. පොයින්ට් ප්‍රමාණය
වැඩිවන විට ඉක්මකයේ ප්‍රමාණය අඩුවිය යුතුය. සාමාන්‍යයෙන් නූතන ෆොන්ට
පොයින්ට් ප්‍රමාණ බොහෝ ගණනක් යටතේ භාවිතා වන මුත් සමහර ෆොන්ට් පවුල්
වලදී වෙනස් වෙනස් පොයින්ට් ප්‍රමාණ සඳහා වන වෙනස් වෙනස් මුහුණත් තිබේ.
එවැනි අවස්ථාවලදී ඉක්මකය මුහුණතින් මුහුණතට වෙනස් ප්‍රමාණ ගනී.

එක්ස් උස (X-height), කැපිටල් උස (Cap-height), නැග්මකය (Ascender),
බැස්මකය (Descender) සහ පාදම් රේඛාව (Baseline) යටතේත් බලන්න.

P

Panose පැනෝස්

විස්තර සහිතව ෆොන්ට අැඳීමට භාවිතාවන පද්ධතියකි. HP’s PANOSE
classification metrics guide බලන්න. මෙයට Panose 2 නමින් වන දිගුවක් ද
අැත.

ෆොන්ට් ෆෝර්ජ් හි අඩංගු වන්නේ ලතින් ෆොන්ට සඳහා වන වර්ගීකරණ පටිපාටි පමණකි.
අනෙකුත් භාෂා වලින් වන ලේඛණ සඳහා අදාලවන වෙනත් පටිපාටි තිබේ.

PfaEdit

ෆොන්ට් ෆෝර්ජ් හි කලින් නම. පළමු දර්ශයේ අැස්කි (ASCII) ෆොන්ට පමණක්
හැඩසවිය හැකිය යන අරුතින් නමෙහි පිළිසිඳගැනීම සිදුවිය. මෘදුකාංගය ඉතා
ඉක්මණින් එතැනින් එහා හැඩසවීම් කටයුතු කිරීම සඳහාත් රූපාන්තරණය වූ නමුත් නම
ෆොන්ට් ෆෝර්ජ් බවට වෙනස්වීම සඳහා වසර තුනක් ගතවිය.

Phantom points ෆැන්ටම් පොයින්ට්/ අවතාර පොයින්ට

සත්‍ය ප්‍රකාර අකුරු මුහුණත් වලදී රූපික සලකුණක් සමඟ එහි පිටත මායිම නිමවීම
සඳහා අදාල නොවන පොයින්ට් කිහිපයක් ද බැඳී තිබෙන අතර එ්වාට ෆැන්ටම්
පොයින්ට් යැයි කියනු ලැබේ. මේවායින් එකක් වමත් පස බෙයාරිම (bearing)
නිරූපණය කරන අතර තවෙකක් රූපික සලකුණේ එකතුවන පළල නිරූපණය කරයි. සත්‍ය
ප්‍රකාර උපදෙස් (ඉඟි) භාවිතය මඟින් අවශ්‍ය වූ විට මෙම පොයින්ට් අනෙක්
පොයින්ට් පරිදිම එහාමෙහා කළ හැකි අතර එසේ කිරීමෙන් රූපික සලකුණේ වමත් පස
බෙයාරිම හෝ එකතුවන පළල වෙනස් කළ හැක. සත්‍ය ප්‍රකාර මාදිලියේ පෙර
සංස්කරණ ඉහත සඳහන් කළ ෆැන්ටම් පොයින්ට් අාකාර දෙක සඳහා පමණක් සහයෝගය
දැක්වුවත් වඩාත් නවීන සංස්කරණ ඉහල පැති බෙයාරිම (top sidebearing) සහ සිරස්
එකතුවන පළල (vertical advance width) යන ෆැන්ටම් පොයින්ට් වලටද සහයෝගය
දක්වයි.

Pica පිකා

සෙන්ටිමීටර 35/83 ක් (දළ වශයෙන් අඟලකින් 1/6 ක්) වනසේ (අවම වශයෙන් එක්සත්
ජනපදය තුල) අර්ථ දක්වන ලද දිග මැනීමේ එ්කකයක්. මුද්‍රිත අකුරු පාඨයක දිග
(‘පිකා 30 කුත් පොයින්ට් 4 ක් දිග’ යනාදී වශයෙන්) මැනීමට භාවිතා කළද මෙම
මිනුම ෆොන්ටයක අකුරු උස මැනීම සඳහා භාවිතා නොවේ.

මැනීමේ එ්කකයක් ලෙස පොයින්ට් හඳුන්වාදීමට පෙර, පුනරුද සමයේ දී අකුරු
මුහුණත් ප්‍රමාණ හැඳින්වීමට (‘පිකා’ වැනි) විශේෂිත නම් සමුදායක් පැවතිණි.
Great Canon, Double Pica, Great Primer, English, Pica, Primer, Small
Pica, Brevier, Nonpareil සහ Pearl වැනි නම් (අනුපිලිවෙලින් මුල සිට අගට
ෆොන්ටයේ ප්‍රමාණය කුඩා වේ) උදාහරණ වේ. තවදුරටත් Wikipedia හි Caslon’s
type specimen sheet වෙබ් පිටුවත් බලන්න.

Pica point පිකා පොයින්ට්

අඟලට පොයින්ට් 72.27 (මිලි මීටරයට පොයින්ට් 2.85) ක් වනසේ අර්ථ දක්වා
අැති අැංග්ලෝ අැමරිකන් පොයින්ට් අගය.

Point පොයින්ට් අගය

‘පොයින්ට්’ යනු මැනීමේ එ්කකයකි. පරිගණක යුගයට පෙර (අවම වශයෙන්) පොයින්ට්
සඳහා අර්ථ දැක්වීම් තුනක් පොදු භාවිතයේ පැවතිනි. අැංග්ලෝ සැක්සන්
මුද්‍රණ ලෝකයේ භාවිතයේ පැවතුනේ “පිකා පොයින්ට්” නම් වූ අඟලට
පොයින්ට් 72.27 (මිලි මීටරයට පොයින්ට් 2.85) ක් වන එ්කකයක් වන අතර
මහාද්වීපයක් ලෙස යුරෝපය පුරා මිලි මීටර 23.566 කට පොයින්ට් 62 2/3 (මිලි
මීටරයට පොයින්ට් 2.66 ක් හෝ අඟලට පොයින්ට් 67.54) ක් වූ ‘ඩිඩො(ට්)
පොයින්ට්’ නම් එ්කකයක් පැවතිනි. ප්‍රංශය සමහර අවස්ථාවලදී අඟලට පොයින්ට්
72.78 (මිලි මීටරයට පොයින්ට් 2.86) ක් වූ ‘මධ්‍යස්ථ පොයින්ට්’ නම්
එ්කකයක් භාවිතා කළේය.

ඩිඩොට් සහ පිකා පොයින්ට් ක්‍රම බොහෝ සැලසුම් කරන ලද එ්වා වූ අතර දෙන
ලද නිශ්චිත පොයින්ට් ප්‍රමාණයක් යටතේ එම පද්ධති දෙක යටතේ වූ එකම පෙළක
කැපිටල් උස (cap-height) අාසන්න වශයෙන් සමාන විය. ලතින් පාදක ඉංග්‍රීසි
නොවන ලේඛණවල අඩංගු වූ උච්චාරණ සළකුණු දැක්වීමට ඩිඩොට් පොයින්ට්
ක්‍රමයේදී කැපිටල් අකුරු වලට ඉහලින් වනසේ අතිරේක හිස් ඉඩක් අෑඳනු
ලැබිණි.

මුද්‍රත පිටුවක පෙළ අන්තර්ගතය සලකන විට, එක් එක් රූපික සලකුණේ තිරස් em
අගයට සාපේක්ෂව සිරස් em අගයෙන් අන්තර්ගතයේ දෘෂ්‍ය රූපය කෙරෙහි සපයන
දායකත්වය පහල අනුපාතයක පවතින ලෙසින් යුරෝපීය භාවිතය සඳහා වූ ෆොන්ටයක්
නිර්මාණය වීම මෙමඟින් ජනිත වූ සිත්ගන්නාසුළු අතුරු ඵලයකි. පරිඝනකවල භාවිතා
කෙරෙන ෆොන්ට මෙම හිස් ඉඩ නොසලකා හරින්නේ යැයි අනුමානයෙන් සිතුවහොත් වර්තමාන
යුරෝපීය මුද්‍රණ යන්ත්‍රවල අකුරු පේලි දෙකක් අතරට යෙදෙන හිස් පරතර
අැතිකිරීමේ සැකැස්ම (leading) වැඩි අගයකට සුසර කෙරෙතැයි සිතිය හැකිය.

දන්නා තරමින් අවම වශයෙන් අැමරිකාව තුලදීවත් පරිඝනක කටයුතු සිදුවන්නේ පිකා
පොයින්ට් (Pica point) අගයට අාසන්න අගයයන් වලදී වන අතර පසු ප්‍රකාර මාදිලිය
භාවිතයට ගන්නේ අඟලකින් ^1^/~72~ ක් වන තරමේ එ්කකයකි/ යුනිටයකි.

අාරම්භයේදී ෆොන්ට එ්වායේ පොයින්ට් ප්‍රමාණය පාදක කොටගෙන හැඳින්වුනේ නැත. එ්
වෙනුවට එ් එ් පොයින්ට් ප්‍රමාණයට කියන නම් තිබිණි. ෆොන්ට උස නම්කිරීම
පිළිබඳව වන පිරිවිතර නිර්ණය කරගැනීමට අවශ්‍ය වූ ව්‍යවහාර වර්ෂ 1730 පමණ
කාලයේ පියරේ ෆෝනියර් (Pierre Fournier) නැමැත්තා විසින් පොයින්ට් ක්‍රමය
හඳුන්වා දෙන ලදී. මෙම ක්‍රමය පසු කලෙක ෆ්රැන්සිස්-අම්බ්‍රොයිස් ඩිඩොට්
(François-Ambroise Didot) විසින් වැඩිදියුණු කරන ලදී (එහෙයින් එය ඔහුගේ
නමින් හැඳින්වේ). ව්‍යවහාර වර්ෂ 1878 දී ‘චිකාගෝ මුද්‍රණ අක්ෂර වාත්තු
මඬුව’ (Chicago Type Foundry) අැමරිකාව තුල පළමු වතාවට පොයින්ට් ක්‍රමයක්
භාවිතා කළේය. ව්‍යවහාර වර්ෂ 1886 දී අැමරිකන් පොයින්ට් ක්‍රමය ප්‍රමිතිගත
කරන ලද අතර පිකා (pica) සෙන්ටිමීටර ^35^/~83~ ක් ලෙස අරුත් දක්වා පිකා
පොයින්ටය (pica point) එයින් ^1^/~12~ ක් වනසේ අරුත් දැක්විණි.

Point Size පොයින්ට් ප්‍රමාණය

ෆොන්ටයක පොයින්ට් ප්‍රමාණය යනු ඊයම් අමුණා නැතිවිට පාදම් රේඛා දෙකක් අතර
පරතරයයි. සාම්ප්‍රදායික මුද්‍රණාක්ෂර විද්‍යාවේදී 10 පොයින්ට් ප්‍රමාණයේ
අකුරු මෝස්තරයක් යනු රූපික සළකුණක් සඳහා වන ලෝහ අච්චු කැටයේ උස
පොයින්ට් 10 ක් වන පරිදි සැකසූ එකම තේමාවේ අමුණන අච්චු අකුරු එකතුවකි.

Point of Inflection නතිවර්තන ලක්ෂ්‍යය

උත්තල හැඩය ගත් වක්‍ර කොටසක් අවතල හැඩය ගත් වක්‍ර කොටසක් සමඟ එක්වනවිට
හෝ අවතල හැඩය ගත් වක්‍ර කොටසක් උත්තල හැඩය ගත් වක්‍ර කොටසක් සමඟ
එක්වනවිට එ් එක්වන ලක්ෂ්‍යයේ ස්වභාවයට කියන නම. ගණිතමය බසින් කියන්නේ නම්
සන්තතික වක්‍රයක් සඳහා d^2^y/ dx^2^ = 0 හෝ අනන්තය වන ලක්ෂ.

ඝනජ සමීකරණ වලින් පැනෙන වක්‍රවල නතිවර්තන ලක්ෂ තිබීමට ඉඩ අැති අතර වර්ගජ
සමීකරණවලින් පැනෙන වක්‍රවල නතිවර්තන ලක්ෂ නොතිබීමට ඉඩ අැත.

PostScript පසුවදන් ප්‍රකාර (භාෂා) මාදිලිය

මුද්‍රණ යන්ත්‍ර බහුතරයක පිටු සැකසුම් භාෂාවක් ලෙස භාවිතා වන කේත සමූහයකි.
භාෂාව එකිනෙකින් වෙනස් අකුරු මුහුණත් රැසක් සඳහා අවශ්‍ය වන පිරිවිතර
රැසකින් සමන්විතය. ෆොන්ට් ෆෝර්ජ් ප්‍රධාන මැනුවලය, පසුවදන් ප්‍රකාර
මාදිලිය සත්‍ය-ප්‍රකාර මාදිලියෙන් වෙනස්වන අාකාරය ගැන විස්තර කර අැති
කොටසකින් සමන්විතය.

පළමු ප්‍රවර්ගය (Type 1) : පසුවදන් ප්‍රකාර මාදිලියේ ෆොන්ට සඳහා වූ පැරණි
සම්මතය මෙයයි. මීට අදාල ෆොන්ට වලට සාමාන්‍යයෙන් අැත්තේ .pfb (හෝ .pfa) ගොනු
නාම දිගුවයි (extension). පළමු ප්‍රවර්ගයේ ෆොන්ටවල එක් බයිටයක් තුල
කේතීකරණයට බඳුන්කළහැකි සීමාව දක්වා රූපික සලකුණු (එනම් රූපික සලකුණු 256
ක්) අන්තර්ගත කළ හැකිය.

දෙවන ප්‍රවර්ගය (Type 2/ CFF) : විවෘත ප්‍රකාර ෆොන්ට තුල භාවිතයට ගැනෙන
අාකෘතිය මෙයයි. මුලුමනින්ම පාහේ පළමු ප්‍රවර්ගය සමඟ සමානවන අයුරක් ගත්තද එය
ගොනු නාම කිහිපයක් සහිත වඩාත් සංයුක්ත වූ අාකෘතියකි. එය සාමාන්‍යයෙන් CFF
වෙළුමක් තුල අැතුලත් වන අතර CFF වෙළුමක් සාමාන්‍යයෙන් විවෘත ප්‍රකාර
ෆොන්ටයක් තුල අන්තර්ගත වේ. මෙම CFF ෆොන්ට අාකෘතිය ද සහයෝගය දක්වන්නේ එක්
බයිටයක් තුල කේතීකරණයට බඳුන්කළහැකි සීමාව දක්වා රූපික සලකුණු වලට පමණක් වන
නමුත් විවෘත ප්‍රකාර වෙළුම වඩාත් සංකීර්ණ කේතීකරණ ක්‍රමවලට පහසුකම් සැපයීම
සඳහා මෙම සීමාව විස්තීරණයට පත් කරයි.

තෙවන ප්‍රවර්ගය (Type 3) : ෆොන්ටයේ සම්පූර්ණ පසුවදන් ප්‍රකාරයටම ඉඩහරින
නමුත් කිසිම ඉඟියකට ඉඩ නොදෙන, එහෙයින් ම කුඩා පොයින්ට් ප්‍රමාණ වලදී
අාකර්ෂණීය ලෙස දෘෂ්‍යමාන වන්නේ නැති ෆොන්ට ප්‍රවර්ගය. තවදුරටත්, බොහෝ
(දෘෂ්‍ය තිර මත ප්‍රතිබිම්බනය සඳහා) පික්සල් බවට හැරවීම කරන මෘදුකාංග
(rasterizers) මෙම ප්‍රවර්ගය සමඟ ගනුදෙනු කිරීමේ අසමත් කමක් දක්වයි. තෙවන
ප්‍රවර්ගයේ ෆොන්ටද එක් බයිටයක් තුල කේතීකරණයට බඳුන්කළහැකි වීමේ සීමාව තෘප්ත
කළයුතුය (උපරිම වශයෙන් කේතීකරණයට බඳුන්කළහැකි රූපික සලකුණු සංඛ්‍යාව 256
කි).

ශුන්‍ය ප්‍රවර්ගය (Type 0) : පළමු, දෙවන හෝ තෙවන ප්‍රවර්ගය යටතට ගැනෙන බොහෝ
උප-ෆොන්ට (sub-fonts) බහු-බයිට කේතීකරණයද (multi-සහිත වඩා විශාල ෆොන්ටයක්
සැකසීම සඳහා එකට එකතුකිරීමට භාවිතාවන ප්‍රවර්ගයයි. CJK හෝ යුනිකෝඩ් ෆොන්ට
සඳහා භාවිතාවිය.

Type 42 : පසුවදන් ප්‍රකාරය තුල වෙළුම්ගත කර අැති සත්‍ය ප්‍රකාර ෆොන්ටයක්.
විවෘත ප්‍රකාරයට විරුද්ධ ස්වභාවයක් අැත.

CID : රූපික සලකුණු අතිවිශාල ප්‍රමාණයක් අැති CJK ෆොන්ට සඳහා භාවිතාවේ.
රූපික සලකුණු ස්වේච්ඡාවෙන් තමුන් පළමු ප්‍රවර්ගයේ හෝ දෙවන ප්‍රවර්ගයේ රූපික
සලකුණු අාකෘතියක් ලෙස නිරූපණය කරගනී. CID ෆොන්ට වල කේතීකරණයක් සිදුවන්නේ
නැති අතර CID අංකයේ සිට රූපික සලකුණට වන අනුරූපණ සබැඳියක් (mapping) පමණක්
අැත. මෙහිදී අවශ්‍යවන පරිදි ගැලපෙන කේතීකරණයන් ලබාදීමට බාහිර CMAP ගොනු
කට්ටලයක් භාවිතාවේ.

Python පයිතන්

කේතවල (මිනිසුන්ට) කියවා තේරුම් ගත හැකි ස්වභාවයෙන් ඉහල බව ‘විශේෂයෙන්
විදහා පෙන්වන’ (උද්ධරණය කෙරෙන) (emphasizes) පරිගණක ක්‍රමලේඛණ භාෂාවකි.

Q

R

Reference අාශ්‍රේය

එක් රූපික සලකුණක පිටත මායිම/ම් වෙනත් රූපික සලකුණක් මත ගබඩා කිරීමේ
ක්‍රමයකි. (උදාහරණ ලෙස උච්චාරණ සලකුණු සහිත රූපික සලකුණු සැකසීම සඳහා) සමහර
අවස්ථාවල සහභාගය (component) ලෙසද හඳුන්වයි.

Right side bearing දකුණු පස බෙයාරිම

රූපික සලකුණක දකුණුපසම ස්ථානය සහ එහි වර්ධිත පළල අතර අැති තිරස් පරතරය. මෙය
ධන හෝ සෘණ අගයක් විය හැකිය.

S

Sans Serif සෑන්ස් සෙරීෆ්

සෙරීෆ් (Serif) යටතේ බලන්න.

Script අක්ෂර මාලාව/ හෝඩිය

අකුරු එකතුවක් එම අකුරු එකිනෙක සමඟ යොදන විට අනුගමනය කළයුතු නීති මාලාව
සමඟ ගත්විට අක්ෂර මාලාවකි (අකුරු මාලාවකි). ලතින්, අරාබි, කතකන සහ හන්ජා
වැනි සියල්ල අක්ෂර මාලාවන් වේ.

Serif සෙරීෆ්

වසර දෙදහසකට පමණ පෙර රෝමානුවන් ඔවුන්ගේ අක්ෂර ශෙෙලමය ස්මාරක මත කොටන
විට අකුරේ ප්‍රධාන කඳවල් අවසන් වන තැන්වලට සියුම් ඉරි එක්කිරීමෙන් ගල්
පුවරුව මත සිදුවන ඉරිතැලීම් හා පැළී යෑම් අවම කළ හැකි බව සොයාගත්හ.

මේ කුඩා ඉරිවලට ‘සෙරීෆ්’ යයි වහරන ලද අතර එ්වා මඟින් ඊටම අනන්‍ය වූ
අලංකාරත්වයක් විදහාපාන බව නිරීක්ෂණය කරන ලදී. එහෙයින් මුල්කාලීන අකුරු
මුහුණත් නිර්මාණ කරුවන් විසින් කෘත්‍යයාත්මක (functional) කරුණු නොසලකා
අලංකාරත්වය උදෙසාම මේ ඉරි ඔවුනගේ අකුරු මුහුණත් වලට එක් කරන ලදී.

දහනමවන සියවසේ අග සහ විසිවන සියවසේ මුල භාගයේ අකුරු මුහුණත්
නිර්මාණකරුවන් විසින් සෙරීෆ් රහිත අකුරු මුහුණත් නිර්මාණය කිරීමට පටන්
ගැනුනු අතර එ්වායේ වූ නුපුරුදු ගතිය නිසා මුල්කාලයේ අස්වාභාවික විකෘතරූප
(Grotesques) සේ සළකන ලදී. පසුව එ්වාට ‘සාන්ස් සෙරීෆ්’ (Sans Serif) යන නම
වැටිණි.

හිබෘෘ වැනි තවත් ලේඛණ ක්‍රමවලද එ්වාට අනන්‍ය වූ සෙරීෆ් ක්‍රම තිබේ. හිබෘෘ
සෙරීෆ් ක්‍රමය ලතින් (සිරිලික්, ග්‍රීක්) ක්‍රමවලින් වෙනස්වන අතර එ්වා රූප
සළකුණක මුදුනට පමණක් අදාල වේ.

SFD (SplineFont Database) ‘පත්කීල’-ෆොන්ට දත්ත ගබඩාව

මෙහි අඩංගු වන්නේ ෆොන්ට් ෆෝර්ජ් ගේම වූ පෞද්ගලික ෆොන්ට නියෝජනයයි. මෙහි
අාකෘතිය මෙහි විස්තර කර අැත. මෙහි අඩංගු ගොනු ASCII වන අතර පහසුවෙන් කියවිය
නොහැකිය. 2008 මැයි 14 වනදා සිට මෙම අාකෘතිය IANA සමඟ MIME මාදිලියක් සඳහා
ලියාපදිංචි කර අැත. (application/vnd.font-fontforgesfd)

අවාසනාවකට මෙන් වෙනත් කරුණු හැඟවීම සඳහාත් ‘sfd’ කෙටියෙදුම භාවිතා කරනු
දකින්නට ලැබේ.

‘හොඳම-10’ (Tops-10) දී, අංකිත PDP-10 මත වන ‘උප ගොනු නාමාවලිය’ (Sub File
Directory) හැඳින්වීමට sfd කෙටි යෙදුම යොදාගනී. ‘හොඳම-10’ මඟින් පරිශීලක
ගොනු නාමාවලි (user file directories) යැයි කියනු ලබන ඉහල මට්ටමේ නිජ
නාමාවලි (top-level (home) directories) සහ උප-නාමාවලි (sub-directories)
අතර විශිෂ්ට භාවය ගොඩනංවයි.

උප ෆොන්ට නිර්වචනය (Sub Font Definition) යන තේරුම ලබාදීම සඳහා ‘TeX’
විසින් භාවිතා කරයි. TeX හි sfd ගොනුවක් තුල, විශාල CJK හෝ යුනිකෝඩ් ෆොන්ට,
TeX (හෝ TeX හි පැරණි සංස්කරණ) සඳහා අවශ්‍ය කරන පරිදි බයිට් එක (1 byte)
බැගින් වන කේතීකරණයන් සහිත කුඩා උප-ෆොන්ට බවට බිඳින්නේ කෙලෙසදැයි සඳහන්වන
තොරතුරු විස්තර අඩංගු වේ.

SFNT

සත්‍ය ප්‍රකාර, විවෘත ප්‍රකාර, අැපල් හි ‘බිට්මැප්’ ප්‍රකාරය (පමණක්), X11
ගේ බිට්මැප් ප්‍රකාරය (පමණක්), අවශිෂ්ඨ typ1 ෆොන්ට සහ අැඩෝබි ගේ SING ෆොන්ට
(සහ නිසැකයෙන්ම අනික්වාත්) අාදී සියල්ල දරන ෆොන්ට කුලකයේ පොදු අාකෘතිය
හැඳින්වීම සඳහා යොදන නම. SFNT අාකෘතිය ෆොන්ට වගු, ගොනුවක් තුල අතුරා අඩංගු
කළයුතු අාකාරය විස්තර කරයි. ඉහත සඳහන් කළ එක් එක් අාකෘතිය මෙම පොදු කුලකයේ
අදහස අනුගමනය කරන නමුත් එකිනෙකින් ස්වාධීන වූ වඩාත් විශේෂ අවශ්‍යතා (අවශ්‍ය
කරන්නේ කුමන අාකාරයේ වගු ද, එ් එ් වගුවේ අන්තර්ගත විය යුත්තේ මොනවා ද යන්න
වැනි) ද තෘප්ත කරයි.

SIP (Supplementary Ideographic Plane) පරිපූරක රූපාක්ෂර තලය

යුනිකෝඩ්හි පරිපූරක රූපාක්ෂර තලය (0x20000 - 0x2FFFF). (තවදුරටත් පොදු
භාවිතයේ නොපවතින) දුර්ලභ හන් අක්ෂර නිරූපනයට යොදාගනී.

වැඩි විස්තර සඳහා;

බීඑම්පී ( BMP ) - මූලික බහුභාෂා තලය (0x00000 - 0x0FFFF)

එස්එම්පී ( SMP ) - පරිපූරක බහුභාෂා තලය (0x10000 - 0x1FFFF)

එස්එස්පී ( SSP ) - පරිපූරක විශේෂ අර්ථ තලය (0xE0000 - 0xEFFFF)

SMP (Supplementary Multilingual Plane) පරිපූරක බහුභාෂා තලය

යුනිකෝඩ්හි පරිපූරක බහුභාෂා තලය (0x10000 - 0x1FFFF). (Linear B, Gothic
සහ Shavian වැනි) පුරාණ සහ කෘත්‍රීම අකාරාදි සහ අක්ෂර මාලා නිරූපනයට
යොදාගනී.

වැඩි විස්තර සඳහා;

බීඑම්පී ( BMP ) - මූලික බහුභාෂා තලය (0x00000 - 0x0FFFF)

එස්අයිපී ( SIP ) - පරිපූරක රූපාක්ෂර (දෘෂ්‍යරූප) තලය (0x20000 - 0x2FFFF)

එස්එස්පී ( SSP ) - පරිපූරක විශේෂ අර්ථ තලය (0xE0000 - 0xEFFFF)

Spline අැලිය

වක්‍ර කොටසක්. ෆොන්ට් ෆෝර්ජ් හි භාවිතාවන සියලු වක්‍ර දෙවන හෝ තෙවන
ගණයේ (වර්ගජ හෝ ඝනජ) බෙසියර් වක්‍ර සහ රාෆ් ලෙවින් ගේ ක්ලොතොයිඩ්
වක්‍ර වේ (Raph Levien’s clothoid splines).

SSP (Supplementary Special-purpose Plane) පරිපූරක විශේෂ අර්ථ තලය

යුනිකෝඩ්හි පරිපූරක විශේෂ අර්ථ තලය (0xE0000 - 0xEFFFF). එතරම් භාවිතයක්
නැත.

වැඩි විස්තර සඳහා;

බීඑම්පී ( BMP ) - මූලික බහුභාෂා තලය (0x00000 - 0x0FFFF)

එස්එම්පී ( SMP ) - පරිපූරක බහුභාෂා තලය (0x10000 - 0x1FFFF)

එස්අයිපී ( SIP ) - පරිපූරක රූපාක්ෂර (දෘෂ්‍යරූප) තලය (0x20000 - 0x2FFFF)

State machine තත්ව යන්ත්‍රය

සංදර්භානුගත අාදේශන සහ ක(ර්)නින් කටයුතු ඉටුකරගැනීමට අැපල් මැක් පරිගණක වල
භාවිතාවන ඉතා සරල කුඩා ක්‍රමලේඛයකි. Element -> Font Info -> Lookups වෙත
යාමෙන් තත්ව යන්ත්‍ර සංවාද කොටුව (State machine Dialog Box) මතුකරගත
හැකිය.

තත්ව යන්ත්‍රය තත්ව අඩංගු වගුවකින් සමන්විතය. ලැබෙන අාදානයට අනුරූපව
පිළිවෙලින් එ් තත්ව (එම තත්වයටම හෝ වෙනත් තත්ව වලට වන) සංක්‍රාන්ති
විභවයන් සහිත ශ්‍රේණියකට යොමු කරනු ලැබේ. ෆොන්ට තුල අැති තත්ව යන්ත්‍ර
‘අැරඹුම් තත්වය’ නම් විශේෂ තත්වයකින් අැරඹී පෙළක් තුල වන රූපික සලකුණු
ප්‍රවාහය කියවමින් තත්ව සංක්‍රාන්තිය සිදුකරයි. සංක්‍රාන්තියේදී තත්ව
යන්ත්‍රය විසින් රූපික සලකුණු ප්‍රවාහය සඳහා කොන්දේසිගත අාදේශන හෝ
ක(ර්)නින් කිරීම සිදුකරයි.

Stem අකුරු කඳ

අකුරු කඳක් යනු අකුරක තිරස් කොටසකි. කැපිටල් අයි ‘I’ සහ සිම්පල් එල් ‘l’
එ්වායේ සෙරීෆ් කොටස් හැරුණුකොට මුලුමනින්ම අකුරු කඳවල් වේ. කැපිටල් එච්
‘H’ අකුරු කඳවල් දෙකකින් සහ හරස් දණ්ඩකින් සමන්විත වේ. B b F f K k P p R
r 1 සහ 4 අකුරු කඳවල් සහිත රූපික සලකුණු වලට තවත් උදාහරණ වේ.

Strike වැද්දුම

ෆොන්ටයකට අදාලවන සුවිශේෂී අවස්ථාවකි (instance). ඉතා පොදුවේ සලකන විට,
බිට්මැප් වැද්දුමක් (bitmap strike) යනු ෆොන්ටයක සුවිශේෂී පික්සල් ප්‍රමාණය
වේ.

Style ශෛලිය

ෆොන්ටයක් සඳහා සම්මත ශෛලීන් ගණනාවක විචලන පවතී. නිසැකවම සලකනු ලබන ඔ්නෑම
භාෂාවක රූපික සලකුණු සඳහා අකුරු කඳවල ඝනකම වෙනස් වන අතර එය ෆොන්ටයක ‘බර
ගතිය’ (weight) ලෙස හඳුන්වයි. සාමාන්‍ය සහ බෝල්ඩ් ලෙස හඳුන්වන්නේ මෙවැනි
නිතර භාවිතාවන බර ගතිය හඳුන්වන යෙදුම් දෙකකි.

LGC (Latin, Greek, Cyrillic එනම් ලතින්, ග්‍රීක්, සිරිලික්) හෝඩිවලදී
ඉටැලික් (හෝ ඔබ්ලික්) ශෛලිය අවධාරණය කොට කියන බව හැඟවීම සඳහා භාවිතා වේ.

ෆොන්ට නිතරම පාහේ සංඝනීකෘත ශෙෙලිය ලබාගැනීමට හකුලවනු ලබන අතර විස්තීරිත
ශෙෙලිය ලබාගැනීමට විහිදුවනු ලැබේ.

විටින් විට භාවිතා කරන අනෙක් ශෙෙලීන් අතර යටින් ඉරක් අැඳීම (underline),
(overstrike),පිට මායිම අැඳීම (outline), සෙවනැලි එක්කිරීම (shadow) යනාදිය
වේ.

SVG (Scalable Vector Graphics) ප්‍රමාණය වෙනස් කළ හැකි දෛශික ග්‍රැෆික්

දෛශික ග්‍රැෆික් අැඳීම සඳහා භාවිතා වන XML අාකෘතියකි. එහි ෆොන්ට අාකෘතියක්ද
අන්තර්ගත ය.

Syllabary සිලබරි/ අක්ෂර සමූහය

උච්චාරණ ශබ්ද මාත්‍රා නිරූපනය කෙරෙන සංකේත මූලික එ්කක ලෙස ගෙන එම එ්කක
එ්කරාශී කිරීමෙන් සකසනු ලබන හෝඩි ස්වරූපයක්. අකාරාදියකදී මූලික එ්කකය ලෙස
ගැනෙන ශබ්ද අණුවකට වෙනස්ව මෙහිදී ශබ්ද මාත්‍රාවක් මූලික එ්කකය ලෙස ගැනෙයි.
ඉංග්‍රීසියෙහි ‘ka’ ලෙස ශබ්ද අණු දෙකකින් නිරූපනය කෙරෙන ‘ක’ ශබ්දය
සිංහලයෙහිදීත් ජපන් කතකන හෝඩියේදීත් ඊට වෙනස්ව තනි රූපික සලකුණකින්
පෙන්විය හැකිය. සිලබරි අක්ෂර එකතු සාමාන්‍යයෙන් අකාරාදී හෝඩිවලට වඩා වැඩි
සංකේත සලකුණු ගණනකින් සමන්විතය. (ජපන් කතකන ක්‍රමයෙන් ලිවීම වෙනස් අක්ෂර
60 කින් පමණ කළහැකි වුවත් කොරියන් හන්ගුල් ක්‍රමයෙන් ලිවීමට වෙනස් අක්ෂර
දස දහස් ගණනක් අවශ්‍ය වේ.)

අබ්ජාඩ් (abjad), අබුගිඩා (abugida), හෝඩිය (alphabet) සහ අදාල විකිපීඩියා
විස්තරය ත් බලන්න.

T

Terminal අග්‍රස්ථය

රූපික සලකුණක අග්‍රස්ථය යනු පාදම් රේඛාවට සාපේක්ෂව ගැනෙන (අක්ෂරය
නිර්මාණය කෙරෙන) ඉරෙහි අවසාන කොටසයි. ‘f’ හි ඉහල අවසාන කොටසේ
අග්‍රස්ථයක් අැත. ‘s’ අකුරට අග්‍රස්ථ දෙකක් තිබේ. රූපික සලකුණක අැති
සෙරීෆ් අග්‍රස්ථ ලෙස නොසලකයි. ‘f” අකුර සෙරීෆ් අාකාරයෙන් අැතිවිට එහි
අාරම්භක කොටස සෙරීෆ් අාකාරයේ විහිදුම් ඉරි සහිත වුවත් එම කොටස
අග්‍රස්ථයක් ලෙස සලකන්නේ නැත. ‘j’ සහ ‘y’ අකුරුවල පහල අවසාන කොටස්
අග්‍රස්ථ ලෙස සැලකේ. 3 ඉලක්කමේ ඉහල සහ පහල අග්‍රස්ථ දෙකක් තිබෙන සේ සලකන
අතර එහි මැද අැත්තේ අග්‍රස්ථයක් නොව සන්ධියකි. විධිමත් තාර්කික පසුබිමක්
මත ගොඩනංවා නැති මේ අාකාරයෙන් වන නාමකරණයන් හුදෙක් සම්මුතිය මත පිහිටා
අැතිකරගත් එ්වා වේ.

TeX

පෙළ සැකසීම සඳහා වන පැකේජයකි.

Thorn

ඉංග්‍රීසි ‘thorn’ වචනයේ පරිදි නිහඬව උච්චාරණය වන ඉංග්‍රීසි ‘th’ ශබ්දය
නිරූපණය කිරීමට ජර්මන් බසේ භාවිතාවන ‘þ’ අකුර. මෙය ග්‍රීක තීටා අකුරේ හඬ
අගයට අාසන්න වශයෙන් සමාන වන බව සිතිය හැක. වර්තමානයේ ඉංග්‍රීසියෙහි ‘the’
වෙනුවට භාවිතාවන ‘ye’ ශබ්දය මෙම රූපික සලකුණේ විකරණය වූ ස්වරූපයක් ලෙස
සැලකිය හැකිය.

තවදුරටත් ‘Eth’ යටතේත් බලන්න.

True-Type සත්‍ය-ප්‍රකාර මාදිලි

අැපල් සමාගම විසින් සංවර්ධනය කර මයික්‍රසොෆ්ට් සමාගම හා බෙදාහදා ගන්නා ලද
අකුරු මුහුණත් ප්‍රකාරයකි. එය ද්විතීය මට්ටමේ (වර්ගජ) බෙzසියර් වක්‍රවල
සැකිල්ල නිරූපනය කරන අතර නව්‍ය ඉඟි පාලක (innovative hinting controls)
වලින් සමන්විත වේ. ප්‍රසාරණය කළ හැකි වගු ශේ‍ර්ණි තුල අකුරු මුහුණත සඳහා
අවශ්‍ය වේ යැයි හැඟෙන අතිරේක තොරතුරු අඩංගු කළ හැක.

ලතින් නොවන හෝඩි සඳහා (හෝ සංකීර්ණ ලතින් හෝඩි සඳහා) අවශ්‍ය වන උසස්
අකුරු රූප විශේෂාංග අන්තර්ගත කිරීමට අැපල් සමාගම සහ අැඩෝබි/
මයිකේ‍රාසොෆ්ට් සමාගම් විසින් මේ වගු විවිධාකාරයෙන් ප්‍රසාරණය කරන ලදී.

වැඩි විස්තර සඳහා ‘ඇපල්’ වර්ධිත අක්ෂර සහ විවෘත-ප්‍රකාර මාදිලි යටතේ
බලන්න.

True Type Tables සත්‍ය-ප්‍රකාර වගු

සෑම සත්‍ය-ප්‍රකාර අකුරු මුහුණත් ගොනුවකම අඩංගු එ් හා බැඳුණු නිශ්චිත
තොරතුරු වලින් සමන්විත වන වගු.

Type 1

පසුවදන් ප්‍රකාරයේ ෆොන්ට අාකාරයකි.

Type 2

විවෘත ප්‍රකාර ෆොන්ට අාවරක තුල භාවිතාවන පසුවදන් ප්‍රකාරයේ ෆොන්ටයකි.

Type 3

පසුවදන් ප්‍රකාරයේ ෆොන්ටවල ඉතා බහුලව භාවිතාවන අාකාරයක්.

Type 0

පසුවදන් ප්‍රකාරයේ ෆොන්ට අාකාරයක්.

Type High

ලෝහ අච්චු අකුරු වලින් මුද්‍රණය කරන සමයේ අච්චු අකුරු ලෝහ කැබැල්ලක
ඝනකම හැඳින්වූ නම. ලෝහ කැබැල්ල මුද්‍රණ යන්ත්‍රය හා සම්බන්ධ වන
වේදිකාවේ සිට (අච්චු අකුර පට්ටල් කර නිමවා අැති) මුද්‍රණය සිදුකරන ලෝහ
මතුපිට දක්වා පරතරය.

Typewriter

Monospace (එකම-ඉඩ ෆොන්ට) යටතේ බලන්න.

U

Unicode යුනිකෝඩ්/ විශ්වකේත

ලෝකයේ දැනට භාවිතාවන සියලුම අක්ෂර එකතුකර කේතීකරණය කිරීමට භාවිතාවන
පද්ධතිය. මෙහි දැනට භාවිතා නොවන ඓතිහාසික අක්ෂර බොහෝමයක්ද අන්තර්ගත
වෙයි. Xxxx

වැඩි විස්තර සඳහා

බීඑම්පී ( BMP ) - මූලික බහුභාෂා තලය (0x00000 - 0x0FFFF)

එස්එම්පී ( SMP ) - පරිපූරක බහුභාෂා තලය (0x10000 - 0x1FFFF)

එස්අයිපී ( SIP ) - පරිපූරක රූපාක්ෂර (දෘෂ්‍යරූප) තලය (0x20000 - 0x2FFFF)

එස්එස්පී ( SSP ) - පරිපූරක විශේෂ අර්ථ තලය (0xE0000 - 0xEFFFF)

යටතේත් බලන්න.

Undershoot අධහ් ඉක්මකය

උපරි ඉක්මකය (Overshoot) යටතේ බලන්න.

UniqueID

පසුවදන් ප්‍රකාර මාදිලියේ ෆොන්ටයක අඩංගු විෂය ක්ෂේත්‍රයකි. අනන්‍ය ලෙස
එ් එ් ෆොන්ටය හඳුනාගැනීමේ යාන්ත්‍රණයක් ලෙස අතීතයේ භාවිතා වූ නමුත් පසුව
අැඩෝබි සමාගම විසින් එහි ශක්‍යතාව මඳ බව තීරණය කරන ලදුව XUID (extended
Unique ID) විෂය ක්ෂේත්‍රය හඳුන්වා දෙන ලදී. නමුත් වර්තමානයේදී අැඩෝබි
විසින් මෙම ක්ෂේත්‍ර දෙකම අනවශ්‍ය බව තීරණය කර අැත.

සත්‍ය ප්‍රකාර මාදිලියේ ‘නාම’ (name) වගුවේ මීට ඉතා සමාන විෂය
ක්ෂේත්‍රයක් තිබේ.

UseMyMetrics

සංයුක්ත රූපික සලකුණක (උදාහරණයක් ලෙස, උච්චාරණ සලකුණු සහිත අකුරක) පළල එය
සමන්විත වන රූපික සලකුණු වලින් එකක (උදාහරණයක් ලෙස, උච්චාරණ සලකුණු භාවිතා
කෙරෙන මූලික අක්ෂරය) පළල ට සමාන වනසේ තබාගැනීමට බලකෙරෙන සත්‍ය ප්‍රකාර
මාදිලියේ සංකල්පයකි.

V

Vertical Advance Width සිරස් එකතුකරනලද පළල

නිරන්තරයෙන් සිරස්ව (කලාතුරකින් තිරස්ව) ලියන චීන, ජපන්, කොරියන් (CJK)
පෙළ සඳහා සෑම රූපාක්ෂරයකටම සිරස් එකතුකරනලද පළලක් මෙන්ම තිරස් එකතුකරනලද
පළලක් ද තිබිය යුතු වේ.

W

Weight වෙ(යි)ට්/ බර ගතිය

ෆොන්ටයක බර ගතිය යනු එහි රූපික සලකුණුවල අැති අකුරු කඳවල ඝනකම (තද ගතිය)
කොපමණද යන බවයි. සාම්ප්‍රදායිකව විවිධ බර ගති ප්‍රමාණ හැඳින්වීමට නම් තිබූ
අතර මෑතක සිට එ් හැඳින්වීමට අංක ක්‍රමයක් භාවිතා වේ.

Thin

100

Extra-Light

200

Light

300

Normal

400

Medium

500

Demi-Bold

600

Bold

700

Heavy

800

Black

900

Nord

Ultra

White space සුදු අවකාශය

පෙළෙහි පේලි දෙකක් අතර ඉඩ, අක්ෂර දෙකක් අතර ඉඩ, වචන දෙකක් අතර ඉඩ, අක්ෂර
තුල ඉඩ යනාදී සියල්ල සුදු අවකාශය ට අයත්වේ. මෙය පුලුල් සහ අාවෘත කරන ලද
තේරුමක් සහිත යෙදුමකි.

Width පළල

තරමක් නොපැහැදිලි තේරුමක් ජනිත කරන යෙදුමක් වන මෙය සමහර අවස්ථාවලදී
‘එකතුකරනලද පළල’ (එක් රූපික සලකුණක අාරම්භයේ සිට ඊළඟ රූපික සලකුණේ
අාරම්භයට අැති දුර) (Advance Width) යන තේරුම දීමටද සමහර අවස්ථාවල වම්පස
බෙයාරිමේ සිට දකුණුපස බෙයාරිමට අැති දුර හැඳින්වීමටද යෙදේ.

X

X-height එක්ස් උස

පාදම් රේඛාවේ සිට ඉහලට මනින සිම්පල් අකුරක උස. (‘o’ වැනි වක්‍ර හිසක්
සහිත අකුරක් හෝ ‘l’ වැනි නැග්මකයක් සහිත අකුරක් හෝ නොසලකා ‘x’ හෝ
‘z’ හෝ ‘v’ වැනි පැතලි හිසක් සහිත අකුරක් සඳහා අරුත් ගැන්වේ.)

කැපිටල් උස (Cap-height), නැග්මකය (Ascender), බැස්මකය (Descender), ඉක්මකය
(Overshoot) සහ පාදම් රේඛාව (Baseline) යටතේ ත් බලන්න.

XUID

පසුවදන් ප්‍රකාර ෆොන්ටයක දිගුකරනලද අනන්‍ය හඳුනාගැනීමේ කේතය (Extended
Unique ID). මේ වනවිට තරමක් දුරට යල්පැන අැත.

අනන්‍ය කේතය (Unique ID) යටතේ ත් බලන්න.

[[anchor]]වැඩි විස්තර සඳහා

යටතේත් බලන්න.

අකුරු රූප (අක්ෂරරූප) Typographic

Traditional Typography මුද්‍රණාක්ෂර විද්‍යාව

ෆොන්ටය/ අකුරු මුහුණත Font/ Font Face

රූපික සලකුණ (රූප සංකේතය/ රූප සලකුණ) Glyph

මාත්‍රාව/ අක්ෂරය Syllable

ශබ්දාණුව Phoneme

අකුර/ අක්ෂරය Character

අකුරේ කඳ Stem

අැස්කි ASCII

වැටිසන Outline

ප්‍රවචනය Rendering

පෙළ Text

ප්‍රකාරය Type(n)

පික්සලය Pixel

පික්සල් බවට හැරවූ Rasterized

(රාස්ටරීකරණය/ රාස්ටරයිසේෂන් Rasterization)

ක්‍රමලේඛය Program

නැංගුරම් ලක්ෂ Anchoring Points

Script ලේඛණය

(Overshoot (උපරි) ඉක්මකය, Undershoot (අධහ්) ඉක්මකය)

Alphabet අකාරාදිය/ හෝඩිය

Syllabary අක්ෂර එකතුව/ අක්ෂර සමූහය

Spline පත්කීලය
